#include "catalogue.h"

const Exercice CATALOGUE[] = {
    {
        "intro1",
        "00_intro",
        "intro1.c",
        "Comment ca marche",
        "Rien a corriger : ce fichier tourne deja.\nOuvre-le, passe PAS_FINI a 0, sauvegarde.\nC'est la boucle que tu repeteras 46 fois.",
        "La ligne est 'const int PAS_FINI = 1;'. Remplace le 1 par un 0.",
        NULL,
    },
    {
        "intro2",
        "00_intro",
        "intro2.c",
        "Lire une erreur du compilateur",
        "Ce fichier ne compile pas. Lis le message ci-dessus : il te donne le fichier,\nla ligne, la colonne et la cause. Corrige, puis passe PAS_FINI a 0.",
        "En C, chaque instruction se termine par un point-virgule.",
        NULL,
    },
    {
        "intro3",
        "00_intro",
        "intro3.c",
        "Lire un rapport du sanitizer",
        "Le programme compile, et pourtant il explose. Le rapport AddressSanitizer\nau-dessus te dit quoi, ou, et de combien tu depasses.\nCorrige l'ecriture fautive.",
        "Un tableau de 4 cases a les indices 0, 1, 2 et 3. Pas 4.",
        NULL,
    },
    {
        "types1",
        "01_types",
        "types1.c",
        "La taille des entiers",
        "sizeof donne la taille d'un type en octets. Complete les valeurs attendues\npour que les verifications passent sur cette machine.",
        "Sur une machine 64 bits classique : char 1, short 2, int 4, long 8.",
        NULL,
    },
    {
        "types2",
        "01_types",
        "types2.c",
        "Le debordement d'entier",
        "Multiplier deux int assez grands deborde, et c'est un comportement indefini :\nUBSan arrete le programme. Le calcul doit se faire en long long.",
        "Il suffit qu'un seul des operandes soit deja un long long pour que la\nmultiplication entiere se fasse en long long : (long long)a * b.",
        NULL,
    },
    {
        "types3",
        "01_types",
        "types3.c",
        "Signe et non signe",
        "Comparer un int a un size_t force l'int a devenir non signe : -1 devient\nun nombre enorme. Corrige la fonction pour qu'elle reponde juste.",
        "Compare les deux valeurs dans le meme monde : convertis la taille en\nlong long, ou teste d'abord que l'indice n'est pas negatif.",
        NULL,
    },
    {
        "types4",
        "01_types",
        "types4.c",
        "Les flottants ne sont pas exacts",
        "0.1 + 0.2 ne vaut pas 0.3 en binaire. Ne compare jamais deux flottants\navec == : compare leur ecart a une tolerance.",
        "VERIFIE_PROCHE(obtenu, attendu, tolerance, message) existe deja.\nUne tolerance de 1e-9 convient ici.",
        NULL,
    },
    {
        "types5",
        "01_types",
        "types5.c",
        "Un char est un nombre",
        "En C, un caractere est un petit entier. 'A' vaut 65, et les lettres se\nsuivent. Ecris la conversion en majuscule sans table ni bibliotheque.",
        "'a' et 'A' sont separes d'un ecart constant : 'a' - 'A'.",
        NULL,
    },
    {
        "types6",
        "01_types",
        "types6.c",
        "La division entiere",
        "int / int donne un int : la partie decimale est jetee avant meme\nd'arriver au double. Convertis au bon moment.",
        "(double)a / b convertit a d'abord. (double)(a / b) convertit trop tard.",
        NULL,
    },
    {
        "flow1",
        "02_controle",
        "flow1.c",
        "if et else",
        "Complete la fonction pour qu'elle renvoie la mention correspondant a la note.\nL'ordre des tests compte.",
        "Teste d'abord le cas le plus restrictif. 16 est aussi superieur a 14.",
        NULL,
    },
    {
        "flow2",
        "02_controle",
        "flow2.c",
        "La boucle for",
        "Ecris la somme des entiers de 1 a n avec une boucle for.\nAttention aux bornes : de 1 a n inclus.",
        "for (int i = 1; i <= n; i++) fait bien n tours, de 1 a n.",
        NULL,
    },
    {
        "flow3",
        "02_controle",
        "flow3.c",
        "while et do-while",
        "Compte combien de fois il faut diviser n par 2 pour arriver a 1.\nLa boucle doit s'arreter : verifie ta condition.",
        "Tant que n est strictement superieur a 1, on divise et on compte.",
        NULL,
    },
    {
        "flow4",
        "02_controle",
        "flow4.c",
        "switch et la chute",
        "Un case sans break tombe dans le suivant. Ici c'est voulu pour les\nvoyelles, et une erreur pour le reste. Repare.",
        "Il manque un break apres le cas des chiffres.",
        NULL,
    },
    {
        "flow5",
        "02_controle",
        "flow5.c",
        "Les operateurs bit a bit",
        "Un entier est un paquet de bits. Ecris les trois operations de base :\nlire un bit, l'allumer, l'eteindre.",
        "Lire : (valeur >> position) & 1. Allumer : valeur | (1u << position).\nEteindre : valeur & ~(1u << position).",
        NULL,
    },
    {
        "fonc1",
        "03_fonctions",
        "fonc1.c",
        "Declarer avant d'utiliser",
        "En C, une fonction doit etre connue avant d'etre appelee.\nAjoute le prototype manquant en haut du fichier.",
        "Un prototype, c'est la signature suivie d'un point-virgule :\nint carre(int n);",
        NULL,
    },
    {
        "fonc2",
        "03_fonctions",
        "fonc2.c",
        "Le passage par valeur",
        "Une fonction C recoit une COPIE de l'argument. Modifier le parametre\nne change rien chez l'appelant. Fais renvoyer la valeur.",
        "Il faut renvoyer le resultat et l'assigner : compteur = incrementer(compteur);",
        NULL,
    },
    {
        "fonc3",
        "03_fonctions",
        "fonc3.c",
        "Modifier par pointeur",
        "Pour qu'une fonction modifie une variable de l'appelant, il faut lui\ndonner son adresse. Complete echanger.",
        "Un pointeur se dereference avec * : *a lit ou ecrit la valeur pointee.\nIl faut une variable temporaire.",
        NULL,
    },
    {
        "fonc4",
        "03_fonctions",
        "fonc4.c",
        "Un tableau en parametre",
        "Un tableau passe en parametre devient un pointeur : sa taille est perdue.\nIl faut la passer a cote.",
        "sizeof(tableau) dans la fonction donne la taille d'un pointeur, pas du\ntableau. Utilise le parametre taille.",
        NULL,
    },
    {
        "fonc5",
        "03_fonctions",
        "fonc5.c",
        "Un pointeur de fonction",
        "Une fonction a une adresse, donc on peut la ranger dans une variable\net la passer en parametre. Complete appliquer.",
        "Le type se lit de l'interieur : int (*operation)(int) est un pointeur\nvers une fonction qui prend un int et renvoie un int.",
        NULL,
    },
    {
        "ptr1",
        "04_pointeurs",
        "ptr1.c",
        "Adresse et dereferencement",
        "& donne l'adresse d'une variable, * lit ou ecrit la valeur a cette adresse.\nComplete la fonction pour qu'elle modifie la variable de l'appelant.",
        "Le parametre est un pointeur : *cible = valeur; ecrit dans la variable pointee.",
        NULL,
    },
    {
        "ptr2",
        "04_pointeurs",
        "ptr2.c",
        "Le pointeur nul",
        "Dereferencer NULL fait planter le programme. Une fonction qui recoit un\npointeur doit se demander s'il peut etre nul.",
        "Teste 'if (pointeur == NULL)' AVANT de faire *pointeur.",
        NULL,
    },
    {
        "ptr3",
        "04_pointeurs",
        "ptr3.c",
        "L'arithmetique de pointeur",
        "Ajouter 1 a un pointeur avance d'UN ELEMENT, pas d'un octet.\nParcours le tableau en deplacant un pointeur.",
        "pointeur + i pointe sur l'element i. *(debut + i) est la meme chose que debut[i].",
        NULL,
    },
    {
        "ptr4",
        "04_pointeurs",
        "ptr4.c",
        "const et pointeurs",
        "const int * : on ne peut pas modifier ce qui est pointe.\nint * const : on ne peut pas faire pointer ailleurs.\nCorrige la signature pour que la fonction promette de ne rien modifier.",
        "La signature doit etre : int maximum(const int *valeurs, size_t taille)",
        NULL,
    },
    {
        "ptr5",
        "04_pointeurs",
        "ptr5.c",
        "Un pointeur sur un pointeur",
        "Pour qu'une fonction change ou pointe un pointeur, il lui faut l'adresse\nde ce pointeur : un int **.",
        "*cible est le pointeur lui-meme, **cible est la valeur pointee.",
        NULL,
    },
    {
        "ptr6",
        "04_pointeurs",
        "ptr6.c",
        "Le pointeur qui pendouille",
        "Renvoyer l'adresse d'une variable locale est un piege : la variable\nn'existe plus au retour. AddressSanitizer le detecte.\nFais ecrire le resultat dans une zone fournie par l'appelant.",
        "Passe un tampon en parametre et ecris dedans, au lieu de renvoyer\nl'adresse d'un tableau local.",
        NULL,
    },
    {
        "ptr7",
        "04_pointeurs",
        "ptr7.c",
        "void* et la conversion",
        "void* est un pointeur sans type : il peut recevoir n'importe quelle adresse,\nmais il faut le reconvertir avant de s'en servir.",
        "Convertis le void* dans le bon type avant de dereferencer :\nconst int *entier = source;",
        NULL,
    },
    {
        "tab1",
        "05_tableaux",
        "tab1.c",
        "Indices et taille",
        "Un tableau de n cases va de l'indice 0 a n-1. Corrige la boucle qui\nrenverse le tableau.",
        "Pour renverser, echange l'element i avec l'element taille - 1 - i,\net arrete-toi au milieu.",
        NULL,
    },
    {
        "tab2",
        "05_tableaux",
        "tab2.c",
        "Sortir des bornes",
        "Cette boucle lit une case de trop. AddressSanitizer te dit exactement\nou et de combien. Corrige la condition d'arret.",
        "Avec i <= taille, le dernier tour lit valeurs[taille], qui n'existe pas.",
        NULL,
    },
    {
        "tab3",
        "05_tableaux",
        "tab3.c",
        "Un tableau n'est pas un pointeur",
        "sizeof d'un tableau donne sa taille totale. sizeof d'un pointeur donne\nla taille d'une adresse. Les deux ne sont pas le meme objet.",
        "sizeof(nombres) / sizeof(nombres[0]) donne le nombre de cases,\nmais seulement la ou le tableau est declare.",
        NULL,
    },
    {
        "tab4",
        "05_tableaux",
        "tab4.c",
        "Deux dimensions",
        "Un tableau 2D est range ligne par ligne, en continu. Complete l'acces\na la case (ligne, colonne).",
        "L'element (l, c) d'un tableau de largeur L est a l'indice l * L + c.",
        NULL,
    },
    {
        "tab5",
        "05_tableaux",
        "tab5.c",
        "Chercher dans un tableau",
        "Renvoie l'indice de la premiere occurrence, ou -1 si absente.\nAttention au type de retour quand rien n'est trouve.",
        "Renvoie un long long ou un int signe : un size_t ne peut pas valoir -1\nsans devenir un nombre enorme.",
        NULL,
    },
    {
        "tab6",
        "05_tableaux",
        "tab6.c",
        "Copier un tableau",
        "Un tableau ne se copie pas avec =. Il faut copier case par case,\nou utiliser memcpy.",
        "memcpy(destination, source, nombre_d_octets). Les octets, pas les cases :\ntaille * sizeof(int).",
        NULL,
    },
    {
        "str1",
        "06_chaines",
        "str1.c",
        "Le zero terminal",
        "Une chaine C, c'est des caracteres suivis d'un octet nul.\nLe tableau doit avoir la place pour ce zero.",
        "\"abc\" occupe 4 octets : 'a', 'b', 'c' et '\\\\0'.",
        NULL,
    },
    {
        "str2",
        "06_chaines",
        "str2.c",
        "Compter sans strlen",
        "Ecris ta propre version de strlen : avance jusqu'au zero terminal.",
        "while (texte[longueur] != '\\\\0') longueur++;",
        NULL,
    },
    {
        "str3",
        "06_chaines",
        "str3.c",
        "strcpy deborde",
        "strcpy ne connait pas la taille de la destination : il ecrit jusqu'au\nzero de la source. Ici ca deborde, et ASan le voit.\nUtilise snprintf, qui prend la taille.",
        "snprintf(destination, sizeof destination, \"%s\", source) ne depasse jamais.",
        NULL,
    },
    {
        "str4",
        "06_chaines",
        "str4.c",
        "Le piege de strncpy",
        "strncpy ne met PAS de zero terminal si la source remplit exactement la\ndestination. Corrige pour garantir une chaine valide.",
        "Apres strncpy, force le dernier octet a zero :\ndestination[taille - 1] = '\\\\0';",
        NULL,
    },
    {
        "str5",
        "06_chaines",
        "str5.c",
        "Comparer deux chaines",
        "== compare deux adresses, pas deux contenus. Pour comparer le texte,\nc'est strcmp, qui renvoie 0 quand c'est egal.",
        "strcmp(a, b) == 0 signifie 'les deux chaines sont identiques'.",
        NULL,
    },
    {
        "str6",
        "06_chaines",
        "str6.c",
        "Construire sans deborder",
        "snprintf renvoie la longueur qu'il AURAIT ecrite. C'est ce qui permet\nde detecter une troncature.",
        "Si la valeur renvoyee est superieure ou egale a la taille du tampon,\nle texte a ete tronque.",
        NULL,
    },
    {
        "str7",
        "06_chaines",
        "str7.c",
        "Parcourir des mots",
        "Compte les mots d'une phrase sans rien allouer : un mot commence quand\non passe d'un espace a autre chose.",
        "Garde un drapeau 'dans_un_mot'. Il passe a 1 au debut d'un mot et\nretombe a 0 sur un espace.",
        NULL,
    },
    {
        "mem1",
        "07_memoire",
        "mem1.c",
        "malloc et free",
        "malloc reserve des octets et renvoie leur adresse, ou NULL si ca rate.\nfree les rend. Complete l'allocation.",
        "Pour n entiers : malloc(n * sizeof(int)). Et teste le retour contre NULL.",
        NULL,
    },
    {
        "mem2",
        "07_memoire",
        "mem2.c",
        "La fuite",
        "Ce programme alloue et oublie de rendre. LeakSanitizer n'existe pas sur\nmacOS : clings compte les blocs a la main avec suivi_malloc et suivi_free.\nRends ce que tu prends.",
        "Il manque un suivi_free avant le return, sur le chemin d'erreur aussi.",
        NULL,
    },
    {
        "mem3",
        "07_memoire",
        "mem3.c",
        "Le double free",
        "Rendre deux fois le meme bloc corrompt l'allocateur. ASan l'attrape.\nUn seul free par malloc.",
        "Enleve le free en trop. Mettre le pointeur a NULL apres free est une\nbonne habitude : free(NULL) ne fait rien.",
        NULL,
    },
    {
        "mem4",
        "07_memoire",
        "mem4.c",
        "Utiliser apres liberation",
        "Lire un bloc deja rendu est un comportement indefini. ASan appelle ca\nun heap-use-after-free. Reordonne le code.",
        "Fais toutes tes lectures AVANT le free.",
        NULL,
    },
    {
        "mem5",
        "07_memoire",
        "mem5.c",
        "realloc",
        "realloc peut deplacer le bloc : il faut reaffecter le pointeur, et ne\njamais ecraser l'ancien avant d'avoir verifie le retour.",
        "int *agrandi = suivi_realloc(bloc, nouvelle_taille);\nif (agrandi == NULL) { ... } else { bloc = agrandi; }",
        NULL,
    },
    {
        "mem6",
        "07_memoire",
        "mem6.c",
        "calloc et la memoire sale",
        "malloc ne remet rien a zero : le bloc contient ce qui trainait.\ncalloc, si. Choisis le bon selon ce que tu fais ensuite.",
        "calloc(nombre, taille) alloue et remplit de zeros.",
        NULL,
    },
    {
        "mem7",
        "07_memoire",
        "mem7.c",
        "Un tableau qui grandit",
        "Ecris la fonction qui ajoute un element, en doublant la capacite quand\nle tableau est plein. C'est le coeur de tout vecteur dynamique.",
        "Quand taille == capacite, double la capacite (minimum 1), realloc,\npuis ecris l'element et incremente taille.",
        NULL,
    },
    {
        "struct1",
        "08_structs",
        "struct1.c",
        "Le point et la fleche",
        "Une struct s'ecrit avec un point, un pointeur vers une struct s'ecrit avec\nune fleche. Le fichier confond les deux : le compilateur te le dit.",
        "point->x est exactement (*point).x. La fleche dereference pour toi.",
        NULL,
    },
    {
        "struct2",
        "08_structs",
        "struct2.c",
        "Le remplissage",
        "Trois champs de 1, 4 et 1 octet ne font pas 6 octets : le compilateur\ninsere du remplissage pour aligner. Complete les valeurs attendues.",
        "Un int veut une adresse multiple de 4. offsetof donne la position d'un\nchamp, _Alignof l'exigence de la struct entiere.",
        NULL,
    },
    {
        "struct3",
        "08_structs",
        "struct3.c",
        "Reordonner les champs",
        "La meme struct, les memes champs, 40 octets ou 24 selon l'ordre.\nReordonne sans rien supprimer.",
        "Du champ le plus exigeant au moins exigeant : les double d'abord,\npuis l'int, puis les char.",
        NULL,
    },
    {
        "struct4",
        "08_structs",
        "struct4.c",
        "Passee par valeur, donc copiee",
        "La fonction travaille sur une copie et jette son travail en sortant.\nDonne-lui l'adresse plutot que la valeur.",
        "Change la signature en Joueur *joueur, le corps en joueur->points,\net l'appel en gagner(&joueur, 20).",
        NULL,
    },
    {
        "struct5",
        "08_structs",
        "struct5.c",
        "L'union et le type tague",
        "Une union ne garde qu'une seule valeur a la fois. Lire un membre autre\nque le dernier ecrit ne veut rien dire : suis le tag.",
        "Un switch sur valeur->genre, et un format par genre : %d, %g, %s.",
        NULL,
    },
    {
        "struct6",
        "08_structs",
        "struct6.c",
        "Les champs de bits",
        "Un champ de n bits ne peut contenir que 2 puissance n valeurs. Deux des\nchamps sont trop etroits pour ce qu'on y range, et la valeur est tronquee.",
        "Pour ranger 5 il faut 3 bits, pour ranger 12 il en faut 4.",
        NULL,
    },
    {
        "struct7",
        "08_structs",
        "struct7.c",
        "Une struct qui possede de la memoire",
        "Copier la struct copie le pointeur, pas le bloc. Les deux entrees\npartagent alors le meme nom, et le liberent deux fois : AddressSanitizer\nt'arrete au second free.",
        "Une copie profonde : alloue un nouveau bloc de la bonne taille avec\nsuivi_malloc, et recopie le texte dedans.",
        NULL,
    },
    {
        "pp1",
        "09_preprocesseur",
        "pp1.c",
        "Une macro est du texte",
        "Le preprocesseur remplace le nom par sa definition, telle quelle, sans\nrien comprendre. Un point-virgule de trop se retrouve donc dans le code.",
        "Regarde ce que devient int tableau[TAILLE] apres substitution.",
        NULL,
    },
    {
        "pp2",
        "09_preprocesseur",
        "pp2.c",
        "Les parentheses autour des parametres",
        "La macro marche pour un nombre et casse pour une expression : l'argument\nest colle tel quel, et la priorite des operateurs fait le reste.",
        "DOUBLE(1 + 2) devient 1 + 2 * 2. Entoure x de parentheses.",
        NULL,
    },
    {
        "pp3",
        "09_preprocesseur",
        "pp3.c",
        "Les parentheses autour du tout",
        "Cette fois les parametres sont proteges, mais pas le resultat.\nCe qui entoure l'appel s'invite dans le calcul.",
        "SOMME(1, 2) * 3 devient (1) + (2) * 3. Il manque une paire de\nparentheses autour de l'expression entiere.",
        NULL,
    },
    {
        "pp4",
        "09_preprocesseur",
        "pp4.c",
        "La double evaluation",
        "La macro ecrit son argument deux fois, donc l'appel a effet de bord se\nfait deux fois. Aucune parenthese ne repare ca.",
        "Remplace la macro par une fonction : les arguments d'une fonction sont\nevalues une fois et une seule.",
        NULL,
    },
    {
        "pp5",
        "09_preprocesseur",
        "pp5.c",
        "do while (0)",
        "Une macro de deux instructions dans un if sans accolades : la premiere\nest conditionnelle, la seconde toujours executee.",
        "Enveloppe le corps dans do { ... } while (0). Ce n'est pas une boucle :\nc'est le seul bloc qui reclame son point-virgule final.",
        NULL,
    },
    {
        "pp6",
        "09_preprocesseur",
        "pp6.c",
        "Mise en chaine, collage, compilation conditionnelle",
        "Deux fautes ici. # ne developpe pas son argument avant de le mettre en\nchaine, et la condition de compilation ecarte la bonne branche.",
        "Pour la mise en chaine il faut deux niveaux de macro. Pour la condition,\nrelis l'operateur : VERSION vaut 3.",
        NULL,
    },
    {
        "mod1",
        "10_modules",
        "mod1.c",
        "Lire une erreur de l'editeur de liens",
        "Trois fichiers cette fois : mod1.c, compteur.c et compteur.h.\nTout compile, et pourtant l'edition de liens echoue. Le message ne parle\nplus de ligne ni de colonne : il parle d'un NOM qu'il ne trouve pas.",
        "L'en-tete promet un nom, le .c en definit un autre. Le compilateur ne\nvoit qu'un fichier a la fois, donc personne ne les compare avant le lien.",
        "compteur.c compteur.h",
    },
    {
        "mod2",
        "10_modules",
        "mod2.c",
        "static, ou le symbole en double",
        "Deux fichiers definissent chacun leur fonction auxiliaire, avec le meme\nnom. L'editeur de liens n'en veut qu'une : duplicate symbol.",
        "Un auxiliaire n'est pas dans l'en-tete, donc il n'est pas dans\nl'interface : marque-le static, dans les deux fichiers.",
        "caisse.c caisse.h",
    },
    {
        "mod3",
        "10_modules",
        "mod3.c",
        "extern, ou la definition dans un en-tete",
        "Un en-tete est copie dans chaque fichier qui l'inclut. Y mettre une\nDEFINITION, c'est donc la creer autant de fois qu'il y a d'inclusions.",
        "Dans l'en-tete : extern int niveau_verbosite; qui declare sans creer.\nDans un seul .c : int niveau_verbosite = 1; qui cree.",
        "config.c config.h",
    },
    {
        "mod4",
        "10_modules",
        "mod4.c",
        "La garde d'inclusion",
        "mod4.c inclut forme.h, puis dessin.h qui inclut forme.h a son tour.\nLe contenu arrive deux fois, et une struct ne se declare pas deux fois.",
        "#ifndef FORME_H / #define FORME_H au debut, #endif a la fin.\nAu second passage, la macro existe et tout est saute.",
        "forme.h dessin.h",
    },
    {
        "mod5",
        "10_modules",
        "mod5.c",
        "Chaque .c inclut son propre .h",
        "couleur.c n'inclut pas couleur.h, donc rien ne verifie que sa definition\ncorrespond a ce que l'en-tete promet. Ca se lie, et ca ment.",
        "Ajoute #include \"couleur.h\" en tete de couleur.c : le compilateur\nsignale alors le conflit, et il ne reste plus qu'a corriger la definition.",
        "couleur.c couleur.h",
    },
    {
        "mod6",
        "10_modules",
        "mod6.c",
        "Le type opaque",
        "poignee.h declare le type sans le definir : struct Poignee reste\nincomplet chez l'appelant. C'est voulu, c'est l'encapsulation du C.\nmod6.c essaie quand meme d'ecrire dans un champ.",
        "Tu ne connais pas la structure, donc tu ne peux pas la toucher :\npasse par poignee_ajouter, qui est justement la pour ca.",
        "poignee.c poignee.h",
    },
    {
        "ub1",
        "11_ub",
        "ub1.c",
        "Le decalage invalide",
        "Decaler un entier de plus de bits qu'il n'en contient n'est pas defini,\net UBSan te dit exactement de combien tu depasses.",
        "Un int fait 32 bits : les decalages valides vont de 0 a 31.\nPour aller plus loin, il faut un type plus large, et un litteral assorti.",
        NULL,
    },
    {
        "ub2",
        "11_ub",
        "ub2.c",
        "La division sans resultat",
        "Deux divisions fautives ici. L'une n'a pas de resultat du tout, l'autre\na un resultat qui ne rentre pas dans le type.",
        "Le quotient de INT_MIN par -1 vaut 2147483648, un de trop pour un int.\nTeste les deux cas avant de diviser, pas apres.",
        NULL,
    },
    {
        "ub3",
        "11_ub",
        "ub3.c",
        "Le flottant qui ne rentre pas",
        "Convertir un double vers un int quand la valeur sort du domaine du int\nn'est pas defini : ce n'est pas une saturation, c'est un trou.",
        "Compare AVANT de convertir, et decide toi-meme de la valeur de repli.",
        NULL,
    },
    {
        "ub4",
        "11_ub",
        "ub4.c",
        "L'adresse mal alignee",
        "Lire un int a une adresse qui n'est pas multiple de 4 n'est pas defini,\nmeme sur un materiel qui l'accepte.",
        "memcpy vers une variable locale correctement alignee : c'est la seule\nfacon portable de lire des octets non alignes, et elle ne coute rien.",
        NULL,
    },
    {
        "ub5",
        "11_ub",
        "ub5.c",
        "La promesse qu'on ne tient pas",
        "__builtin_unreachable() promet au compilateur qu'un point du code n'est\njamais atteint, et il optimise a partir de cette promesse. UBSan, lui,\nverifie qu'elle est tenue.",
        "Ne promets rien : renvoie une vraie valeur pour le dernier cas.\nA noter au passage : en C, tomber sur l'accolade fermante sans return\nn'est signale que par -Wreturn-type. UBSan ne le voit pas, -fsanitize=return\nne couvre que le C++.",
        NULL,
    },
    {
        "ub6",
        "11_ub",
        "ub6.c",
        "La valeur qui n'existe pas dans le type",
        "Un _Bool ne contient que 0 ou 1. Y ranger 2 par un chemin detourne\nfabrique une valeur que le type n'admet pas, et la relecture explose.",
        "Normalise avant de ranger : ecris valeur != 0, pas les octets bruts.",
        NULL,
    },
    {
        "alloc1",
        "12_allocateurs",
        "alloc1.c",
        "Le pointeur qui avance",
        "Un allocateur en dix lignes : un tampon, un curseur, une addition par\nallocation. Il ne sait pas encore dire non, et il deborde.",
        "Avant de servir, compare la taille demandee a ce qu'il reste.\nUn allocateur qui n'a plus de place renvoie NULL, il ne triche pas.",
        NULL,
    },
    {
        "alloc2",
        "12_allocateurs",
        "alloc2.c",
        "L'alignement",
        "Le curseur avance de la taille exacte, donc l'adresse rendue pour un\ndouble tombe n'importe ou. UBSan arrete le programme a l'ecriture.",
        "Arrondis le curseur au multiple superieur de l'alignement demande.\nPour une puissance de deux : (curseur + a - 1) & ~(a - 1).",
        NULL,
    },
    {
        "alloc3",
        "12_allocateurs",
        "alloc3.c",
        "L'arene et le marqueur",
        "Une arene rend tout ce qui a ete pris depuis un point, en une seule\noperation. Ici la restauration ne restaure rien.",
        "Le marqueur n'est que la position du curseur. Restaurer, c'est le\nremettre a cette position : la memoire au-dela redevient libre.",
        NULL,
    },
    {
        "alloc4",
        "12_allocateurs",
        "alloc4.c",
        "La liste libre",
        "Un pool de blocs de taille fixe, chaines entre eux quand ils sont libres.\nLiberer ne remet rien dans la liste, donc le pool se vide et ne se\nremplit jamais.",
        "Un bloc libre ne sert a rien : sers-t'en pour ranger l'adresse du\nsuivant. Liberer, c'est le rechainer en tete.",
        NULL,
    },
    {
        "alloc5",
        "12_allocateurs",
        "alloc5.c",
        "L'en-tete de bloc",
        "C'est ainsi que free se passe de la taille : elle est rangee juste avant\nle pointeur qu'on t'a rendu. Ici la place de l'en-tete n'est pas comptee.",
        "Reserve taille + sizeof(En_tete), ecris l'en-tete au debut, et rends\nl'adresse qui suit. Pour liberer, recule du meme nombre d'octets.",
        NULL,
    },
    {
        "alloc6",
        "12_allocateurs",
        "alloc6.c",
        "Brancher l'arene sur du vrai code",
        "Une allocation par chaine, et un chemin de sortie qui en oublie : la\nfuite est structurelle, pas distraite.",
        "Prends la memoire en une fois, rends-la en une fois. Une arene ne peut\npas fuir par oubli : il n'y a rien a oublier.",
        NULL,
    },
    {
        "ds1",
        "13_structures",
        "ds1.c",
        "Le vecteur generique",
        "Le meme vecteur doit servir pour des int et pour une struct. Il connait\nla taille d'un element, mais il oublie de s'en servir pour calculer les\nadresses.",
        "L'adresse du ieme element, c'est (char *)donnees + i * taille_element.\nLe cast en char * est ce qui rend l'arithmetique possible en octets.",
        NULL,
    },
    {
        "ds2",
        "13_structures",
        "ds2.c",
        "Les indices, pas les pointeurs",
        "Un pointeur pris avant un ajout, utilise apres : entre les deux, le\nvecteur a grandi et deplace son bloc. AddressSanitizer le voit.",
        "Un indice survit a la reallocation, un pointeur non. Garde l'indice et\nrecalcule l'adresse au moment de t'en servir.",
        NULL,
    },
    {
        "ds3",
        "13_structures",
        "ds3.c",
        "Le pointeur de pointeur",
        "Supprimer dans une liste chainee avec un cas particulier pour la tete :\nc'est la version qu'on ecrit d'abord, et celle qui casse.",
        "Ne garde pas le noeud precedent, garde l'ADRESSE du pointeur qui mene\nau noeud courant : Noeud **curseur = &tete. La tete cesse d'etre un cas.",
        NULL,
    },
    {
        "ds4",
        "13_structures",
        "ds4.c",
        "L'adressage ouvert",
        "Sondage lineaire : quand la case est prise, on essaie la suivante. Mais\nil faut revenir au debut du tableau, et ici la boucle continue tout droit.",
        "L'indice suivant, c'est (indice + 1) % capacite. Le tableau est un\ncercle, pas une ligne.",
        NULL,
    },
    {
        "ds5",
        "13_structures",
        "ds5.c",
        "La pierre tombale",
        "Supprimer en remettant la case a VIDE coupe la chaine de sondage : une\ncle rangee plus loin a cause d'une collision devient introuvable.",
        "Marque la case SUPPRIMEE plutot que VIDE : la recherche la traverse,\nl'insertion peut la reutiliser.",
        NULL,
    },
    {
        "ds6",
        "13_structures",
        "ds6.c",
        "Le facteur de charge",
        "La table ne grandit jamais. Plus elle se remplit, plus les sondages\ns'allongent, jusqu'a l'echec.",
        "Au-dela d'un taux d'occupation choisi, double la capacite et REHACHE\ntout : les indices dependent de la capacite, on ne peut pas recopier.",
        NULL,
    },
};

const int CATALOGUE_TAILLE = (int)(sizeof CATALOGUE / sizeof CATALOGUE[0]);

const Question QUESTIONS[] = {
    {
        "00_intro",
        "Que fait exactement AddressSanitizer ?",
        {
            "Il corrige les erreurs memoire automatiquement",
            "Il ajoute des verifications autour de chaque acces memoire, a l'execution",
            "Il analyse le code source sans le lancer",
            "Il empeche le programme de compiler s'il y a un bug",
        },
        1,
        "ASan instrumente le programme a la compilation : chaque lecture et chaque\necriture verifie une carte des zones valides. C'est une verification a\nl'EXECUTION, donc elle ne voit que les chemins reellement parcourus.",
    },
    {
        "00_intro",
        "Un tableau declare 'int t[4]' a quels indices valides ?",
        {
            "0 a 4",
            "1 a 4",
            "0 a 3",
            "1 a 3",
        },
        2,
        "Quatre cases, numerotees a partir de zero : 0, 1, 2, 3. t[4] est hors\nbornes, et c'est la faute la plus frequente du langage.",
    },
    {
        "01_types",
        "Que vaut 7 / 2 en C, avec deux int ?",
        {
            "3.5",
            "3",
            "4",
            "cela depend du compilateur",
        },
        1,
        "La division de deux entiers est une division entiere : la partie decimale\nest jetee, pas arrondie. Pour obtenir 3.5 il faut convertir AVANT :\n(double)7 / 2.",
    },
    {
        "01_types",
        "Pourquoi 'if (-1 < taille)' peut etre faux quand taille est un size_t ?",
        {
            "Parce que size_t est plus petit qu'un int",
            "Parce que -1 est converti en un tres grand nombre non signe",
            "Parce que la comparaison est indefinie",
            "Parce que le compilateur inverse l'operateur",
        },
        1,
        "Quand on compare un type signe et un type non signe de meme rang ou plus\ngrand, le signe est converti vers le non signe. -1 devient 18446744073709551615.\nC'est un bug classique, et le compilateur le signale avec -Wsign-compare.",
    },
    {
        "01_types",
        "Le debordement d'un int signe est :",
        {
            "Un enveloppement (wrap) garanti",
            "Un comportement indefini",
            "Une erreur de compilation",
            "Une exception a l'execution",
        },
        1,
        "Le debordement signe est un comportement indefini : le compilateur a le\ndroit de supposer qu'il n'arrive jamais et d'optimiser en consequence.\nLe debordement NON signe, lui, est defini et enveloppe.",
    },
    {
        "02_controle",
        "Que fait un 'case' sans 'break' dans un switch ?",
        {
            "Il sort du switch",
            "Il tombe dans le case suivant",
            "C'est une erreur de compilation",
            "Il repart au debut du switch",
        },
        1,
        "C'est la chute (fallthrough). Parfois voulue pour regrouper des cas,\nsouvent un oubli. Les compilateurs modernes savent le signaler avec\n-Wimplicit-fallthrough.",
    },
    {
        "02_controle",
        "Que vaut (1u << 3) ?",
        {
            "3",
            "6",
            "8",
            "16",
        },
        2,
        "Decaler 1 de n positions vers la gauche revient a multiplier par 2 puissance n.\n1 << 3 vaut 8. C'est la base de tous les masques de bits.",
    },
    {
        "03_fonctions",
        "Une fonction C recoit ses arguments :",
        {
            "Par reference",
            "Par copie",
            "Par reference si c'est un tableau",
            "Cela depend du compilateur",
        },
        1,
        "Toujours par copie. Un pointeur est copie lui aussi : c'est l'ADRESSE qui\nest dupliquee, ce qui permet quand meme de modifier ce qu'elle designe.\nUn tableau, lui, se convertit en pointeur avant d'etre copie.",
    },
    {
        "03_fonctions",
        "Que donne sizeof(t) dans 'void f(int t[10])' ?",
        {
            "40",
            "10",
            "la taille d'un pointeur",
            "erreur de compilation",
        },
        2,
        "Le parametre n'est PAS un tableau : le [10] est decoratif, le compilateur\nle transforme en int*. sizeof donne donc la taille d'une adresse.\nC'est pour cela qu'on passe toujours la taille a cote.",
    },
    {
        "04_pointeurs",
        "Que fait 'pointeur + 1' sur un int* ?",
        {
            "Avance d'un octet",
            "Avance de 4 octets sur une machine ou int fait 4",
            "Avance d'un bit",
            "Provoque une erreur",
        },
        1,
        "L'arithmetique de pointeur compte en ELEMENTS, pas en octets. Le compilateur\nmultiplie par sizeof du type pointe. C'est ce qui rend p[i] equivalent a\n*(p + i).",
    },
    {
        "04_pointeurs",
        "Renvoyer l'adresse d'une variable locale, c'est :",
        {
            "Legal et pratique",
            "Legal mais lent",
            "Un pointeur vers une zone qui n'existe plus",
            "Interdit par le compilateur",
        },
        2,
        "La variable vit dans le cadre de pile de la fonction, detruit au retour.\nL'adresse reste valide syntaxiquement mais ne designe plus rien :\nc'est un pointeur pendouillant. ASan le detecte en mode\ndetect_stack_use_after_return.",
    },
    {
        "04_pointeurs",
        "A quoi sert 'const' dans 'const int *p' ?",
        {
            "p ne peut pas changer de cible",
            "on ne peut pas modifier *p",
            "les deux",
            "aucun des deux, c'est decoratif",
        },
        1,
        "const int *p : la VALEUR pointee est en lecture seule, mais p peut pointer\nailleurs. int * const p : l'inverse. Lis de droite a gauche a partir du nom.",
    },
    {
        "05_tableaux",
        "sizeof(t) / sizeof(t[0]) donne le nombre de cases :",
        {
            "toujours",
            "seulement la ou le tableau est declare",
            "seulement pour les tableaux de char",
            "jamais, c'est une legende",
        },
        1,
        "Des que le tableau est passe a une fonction, il devient un pointeur et\nl'astuce donne un resultat faux, souvent 1 ou 2. Elle ne vaut que dans\nla portee ou le tableau est declare.",
    },
    {
        "05_tableaux",
        "Comment copier un tableau de 4 int ?",
        {
            "copie = source;",
            "memcpy(copie, source, 4);",
            "memcpy(copie, source, sizeof source);",
            "copie[] = source[];",
        },
        2,
        "memcpy compte en OCTETS. Passer 4 ne copie que le premier int.\nsizeof source donne bien 16 sur une machine ou int fait 4.",
    },
    {
        "06_chaines",
        "Combien d'octets occupe la chaine \"abc\" ?",
        {
            "3",
            "4",
            "6",
            "cela depend de l'encodage",
        },
        1,
        "Trois caracteres plus l'octet nul de fin. Oublier de compter ce zero est\nla cause numero un des debordements de tampon en C.",
    },
    {
        "06_chaines",
        "Quel est le piege de strncpy ?",
        {
            "Elle est plus lente que strcpy",
            "Elle n'ecrit pas de zero terminal si la source remplit la destination",
            "Elle refuse les chaines vides",
            "Elle alloue de la memoire",
        },
        1,
        "strncpy remplit exactement n octets. Si la source fait n caracteres ou plus,\nil n'y a pas de place pour le zero, et la 'chaine' obtenue n'en est pas une.\nEn pratique, prefere snprintf.",
    },
    {
        "06_chaines",
        "Que compare 'if (a == b)' quand a et b sont des char* ?",
        {
            "Le contenu des chaines",
            "Les deux adresses",
            "La longueur des chaines",
            "Le premier caractere",
        },
        1,
        "Ce sont deux pointeurs : on compare des adresses. Pour comparer le contenu,\nc'est strcmp, qui renvoie 0 quand les chaines sont identiques.",
    },
    {
        "07_memoire",
        "Que contient un bloc juste renvoye par malloc ?",
        {
            "Des zeros",
            "Ce qui trainait a cet endroit de la memoire",
            "Des valeurs aleatoires garanties",
            "Le contenu du bloc precedemment libere",
        },
        1,
        "malloc ne promet rien sur le contenu. Lire un bloc non initialise est un\ncomportement indefini. calloc, lui, garantit des zeros, au prix d'un\nremplissage.",
    },
    {
        "07_memoire",
        "Que faire si realloc renvoie NULL ?",
        {
            "Rien, le bloc a ete libere",
            "Le bloc d'origine est toujours valide et doit etre libere",
            "Recommencer immediatement",
            "Le programme s'arrete tout seul",
        },
        1,
        "En cas d'echec, realloc ne touche pas au bloc d'origine. Ecrire\n'bloc = realloc(bloc, n)' perd donc l'ancienne adresse et fuit :\nil faut passer par une variable temporaire.",
    },
    {
        "07_memoire",
        "Pourquoi mettre un pointeur a NULL apres free ?",
        {
            "Pour liberer plus vite",
            "Pour que free soit appele deux fois sans risque",
            "Parce que le compilateur l'exige",
            "Pour economiser de la memoire",
        },
        1,
        "free(NULL) est defini et ne fait rien. Mettre le pointeur a NULL apres\nliberation transforme donc un double free en operation inoffensive, et\nrend les utilisations apres liberation plus faciles a reperer.",
    },
    {
        "07_memoire",
        "Pourquoi doubler la capacite d'un tableau dynamique ?",
        {
            "Pour economiser la memoire",
            "Pour que le cout moyen d'un ajout reste constant",
            "Parce que realloc l'exige",
            "C'est arbitraire",
        },
        1,
        "En doublant, le nombre de reallocations pour n ajouts est proportionnel a\nlog n, et le cout total des copies reste proportionnel a n : chaque ajout\ncoute donc un temps constant en moyenne. Agrandir de 1 a chaque fois\ndonnerait un cout total en n au carre.",
    },
    {
        "08_structs",
        "Pourquoi struct { char; int; char; } occupe-t-elle 12 octets et non 6 ?",
        {
            "Le compilateur reserve de la marge au cas ou",
            "Chaque champ est aligne, et la struct est completee a la fin",
            "Un char occupe 4 octets dans une struct",
            "Parce que la struct n'a pas de nom",
        },
        1,
        "Un int veut une adresse multiple de 4 : trois octets de remplissage apres le\npremier char. Et la struct doit pouvoir s'aligner dans un tableau, donc sa\ntaille est completee au multiple de son alignement : trois octets de plus a la\nfin. Reordonner les champs du plus exigeant au moins exigeant supprime les deux.",
    },
    {
        "08_structs",
        "Lire un membre d'union autre que celui qu'on vient d'ecrire :",
        {
            "Convertit la valeur vers le type demande",
            "Reinterprete les memes octets, et n'est pas defini en general",
            "Renvoie toujours zero",
            "Est refuse par le compilateur",
        },
        1,
        "Une union n'a qu'une case : tous ses membres commencent a la meme adresse.\nLa norme ne garantit la relecture que pour la sequence initiale commune de\nstructs. D'ou le type tague : un enum a cote qui dit quel membre est valide,\net un switch qui le respecte.",
    },
    {
        "08_structs",
        "Que copie 'Entree copie = original;' quand Entree contient un char * ?",
        {
            "Le texte pointe, dans un nouveau bloc",
            "L'adresse seulement : les deux structs partagent le meme bloc",
            "Rien, l'affectation de struct n'existe pas",
            "Cela depend du compilateur",
        },
        1,
        "L'affectation de struct copie les octets des champs, donc le pointeur.\nLes deux structs designent alors le meme bloc, et le liberer des deux cotes\nest un double free. Le C ne fait jamais de copie profonde tout seul : c'est\na toi de l'ecrire, et de le documenter.",
    },
    {
        "09_preprocesseur",
        "Avec #define CARRE(x) (x) * (x), que vaut 12 / CARRE(2) ?",
        {
            "3",
            "12",
            "6",
            "Une erreur de compilation",
        },
        1,
        "Les parametres sont proteges, mais pas le resultat : 12 / (2) * (2) se lit\nde gauche a droite et vaut 12. Il faut les deux niveaux de parentheses,\nautour de chaque parametre ET autour de l'expression entiere : ((x) * (x)).",
    },
    {
        "09_preprocesseur",
        "Pourquoi enveloppe-t-on une macro de plusieurs instructions dans do { } while (0) ?",
        {
            "Pour qu'elle soit plus rapide",
            "Pour qu'elle se comporte comme une seule instruction, point-virgule compris",
            "Pour que le corps s'execute au moins une fois",
            "Pour eviter le remplissage",
        },
        1,
        "De simples accolades laisseraient un point-virgule orphelin apres l'appel,\nce qui casse le else d'un if. do { ... } while (0) est le seul bloc qui\nreclame son point-virgule final : c'est donc le seul qui s'utilise\nexactement comme un appel de fonction.",
    },
    {
        "09_preprocesseur",
        "Avec #define TEXTE(x) #x et #define VERSION 3, que vaut TEXTE(VERSION) ?",
        {
            "La chaine \"3\"",
            "La chaine \"VERSION\"",
            "L'entier 3",
            "Une erreur de compilation",
        },
        1,
        "L'operateur # met en chaine son argument AVANT tout developpement.\nPour obtenir \"3\" il faut un niveau de plus : TEXTE(x) qui appelle\nTEXTE_BRUT(x), car les arguments sont developpes au passage d'une macro\na une autre. C'est le seul endroit du langage ou l'ordre est visible.",
    },
    {
        "10_modules",
        "Que compare l'editeur de liens quand il assemble deux fichiers objet ?",
        {
            "Les types des fonctions",
            "Rien d'autre que des noms de symboles",
            "Les prototypes trouves dans les en-tetes",
            "Le contenu des en-tetes inclus",
        },
        1,
        "Il ne voit que des noms et des adresses : les types ont disparu a la\ncompilation. C'est pour ca qu'une declaration qui ne correspond pas a sa\ndefinition se lie sans un mot et casse a l'execution, et c'est pour ca que\nchaque .c doit inclure son propre .h : le compilateur, lui, sait comparer.",
    },
    {
        "10_modules",
        "Que fait 'static' devant une fonction de portee fichier ?",
        {
            "Elle garde son etat entre deux appels",
            "Elle devient invisible aux autres unites de traduction",
            "Elle est rangee en memoire statique",
            "Elle est plus rapide",
        },
        1,
        "static donne la liaison interne : le symbole n'est pas exporte, donc deux\nfichiers peuvent avoir chacun leur fonction du meme nom sans se gener.\nAttention au faux ami : sur une variable LOCALE, static veut dire tout autre\nchose, une duree de vie qui couvre tout le programme.",
    },
    {
        "10_modules",
        "Que met-on dans un en-tete pour une variable globale partagee ?",
        {
            "int compteur = 0;",
            "extern int compteur;",
            "static int compteur;",
            "rien, une globale ne se partage pas",
        },
        1,
        "Un en-tete est recopie dans chaque fichier qui l'inclut : une definition y\ndevient autant de definitions, et l'editeur de liens refuse. extern declare\nsans creer, et la definition va dans un seul .c. 'static' serait pire encore :\nchaque fichier aurait SA variable, et ca se lierait sans erreur.",
    },
    {
        "11_ub",
        "Quelle est la difference entre comportement indefini et non specifie ?",
        {
            "Aucune, ce sont deux mots pour la meme chose",
            "Non specifie laisse le choix entre plusieurs comportements corrects ; indefini n'impose rien du tout",
            "Indefini plante toujours, non specifie jamais",
            "Non specifie ne concerne que les flottants",
        },
        1,
        "Non specifie, la norme laisse le choix entre plusieurs comportements valides,\ncomme l'ordre d'evaluation des arguments. Indefini, elle ne promet rien : le\ncompilateur a le droit de SUPPOSER que ca n'arrive pas et d'optimiser a partir\nde la. C'est cette supposition qui fait disparaitre du code.",
    },
    {
        "11_ub",
        "Pourquoi un debordement d'entier signe peut-il rendre une boucle infinie ?",
        {
            "Parce que le compteur revient a zero et repart",
            "Parce que le compilateur suppose qu'il n'arrive pas et supprime le test de sortie",
            "Parce que le processeur leve une exception",
            "C'est une legende, ca n'arrive pas",
        },
        1,
        "Le debordement signe etant indefini, le compilateur en deduit que i + 1 est\ntoujours superieur a i, donc qu'un test comme i + 1 > i est toujours vrai, et\nil l'enleve. Ce n'est pas un bug du compilateur, c'est le contrat. -fwrapv\ndefinit le debordement et supprime la deduction, pour quelques pourcents.",
    },
    {
        "11_ub",
        "Un programme qui passe AddressSanitizer et UBSan est-il correct ?",
        {
            "Oui, c'est une preuve",
            "Non : ils ne verifient que les chemins reellement executes",
            "Oui, des que les tests couvrent toutes les lignes",
            "Non, ils ne detectent rien d'utile",
        },
        1,
        "Les sanitizers instrumentent l'execution : ce qui n'est pas execute n'est pas\nverifie, et d'autres donnees peuvent reveiller le meme bug. Ils n'ont pas non\nplus de detecteur pour tout : la lecture non initialisee demande MSan, et les\nfuites demandent LeakSanitizer, absent sur macOS ARM.",
    },
    {
        "11_ub",
        "En C, que fait UBSan quand une fonction non-void tombe sur son accolade fermante ?",
        {
            "Il arrete le programme, comme pour les autres fautes",
            "Rien : -fsanitize=return ne couvre que le C++, seul -Wreturn-type previent",
            "Il renvoie zero a la place",
            "Il refuse de compiler",
        },
        1,
        "C'est un des trous a connaitre. En C++ le sanitizer attrape le cas ; en C il\nest muet, et la fonction rend ce qui trainait dans le registre de retour, sans\nun mot. L'avertissement -Wreturn-type, actif dans -Wall, est la seule barriere,\net c'est une bonne raison de traiter les avertissements en erreurs.",
    },
    {
        "12_allocateurs",
        "Pourquoi ecrire son allocateur, en general ?",
        {
            "Parce que malloc est lent",
            "Pour changer la duree de vie et le nombre d'appels, pas la vitesse d'un appel",
            "Pour economiser de la memoire",
            "Parce que malloc n'est pas portable",
        },
        1,
        "malloc est tres bien ecrit ; le battre sur un appel isole est difficile et sans\ninteret. Ce qu'un allocateur specialise apporte, c'est de rendre mille blocs en\nune operation, de supprimer par construction la fuite et le double free a\nl'interieur d'un cycle, et de remplacer mille appels par un seul.",
    },
    {
        "12_allocateurs",
        "Comment arrondir un curseur a un alignement puissance de deux ?",
        {
            "curseur + alignement",
            "(curseur + alignement - 1) & ~(alignement - 1)",
            "curseur * alignement",
            "curseur % alignement",
        },
        1,
        "On ajoute alignement - 1 pour depasser, puis on efface les bits de poids\nfaible avec le masque complementaire. La version generale, valable meme si\nl'alignement n'est pas une puissance de deux, s'ecrit\n(curseur + a - 1) / a * a, mais elle coute une division.",
    },
    {
        "12_allocateurs",
        "Ou range-t-on la liste des blocs libres d'un pool a taille fixe ?",
        {
            "Dans un tableau a cote",
            "Dans les blocs libres eux-memes",
            "Dans une table de hachage",
            "Nulle part, on parcourt tout",
        },
        1,
        "Un bloc libre ne contient rien d'utile : on y range l'adresse du bloc libre\nsuivant. La liste ne coute donc pas un octet de plus, allouer c'est prendre la\ntete, liberer c'est rechainer en tete, et les deux sont en temps constant.",
    },
    {
        "13_structures",
        "Pourquoi garder des indices plutot que des pointeurs dans un tableau dynamique ?",
        {
            "Un indice prend moins de place",
            "Un indice survit a la reallocation, un pointeur non",
            "Un pointeur est plus lent a dereferencer",
            "C'est une question de style",
        },
        1,
        "Quand le tableau grandit, il peut prendre un nouveau bloc et deplacer tout son\ncontenu : chaque pointeur vers l'interieur devient pendouillant. L'indice, lui,\ndesigne une position, pas une adresse, et reste valide. La place gagnee est un\nbonus, pas la raison.",
    },
    {
        "13_structures",
        "Pourquoi ne peut-on pas remettre une case a VIDE en supprimant, dans une table a adressage ouvert ?",
        {
            "Parce que la case serait reutilisee trop vite",
            "Parce que la chaine de sondage serait coupee, et les cles suivantes introuvables",
            "Parce que le hachage changerait",
            "Parce que la capacite doit rester constante",
        },
        1,
        "Une cle placee plus loin a cause d'une collision n'est retrouvee qu'en\ntraversant les cases intermediaires. Une case VIDE arrete la recherche : tout\nce qui etait derriere devient invisible. D'ou la pierre tombale, une marque que\nla recherche traverse et que l'insertion peut reutiliser.",
    },
    {
        "13_structures",
        "Que faut-il faire en doublant la capacite d'une table de hachage ?",
        {
            "Recopier les cases dans l'ordre",
            "Rehacher chaque cle et la replacer",
            "Rien, les indices restent valides",
            "Trier les cles",
        },
        1,
        "L'indice d'une cle se calcule modulo la capacite : changer la capacite change\ntous les indices. Une recopie a l'identique rendrait la table incoherente. Le\nrehachage coute cher, ce qui est justement la raison pour laquelle on double\nplutot que d'agrandir d'un cran.",
    },
};

const int QUESTIONS_TAILLE = (int)(sizeof QUESTIONS / sizeof QUESTIONS[0]);
