#include "catalogue.h"

const Exercice CATALOGUE[] = {
    {
        "intro1",
        "00_intro",
        "intro1.c",
        "Comment ca marche",
        "Rien a corriger : ce fichier tourne deja.\nOuvre-le, passe PAS_FINI a 0, sauvegarde.\nC'est la boucle que tu repeteras 46 fois.",
        "La ligne est 'const int PAS_FINI = 1;'. Remplace le 1 par un 0.",
    },
    {
        "intro2",
        "00_intro",
        "intro2.c",
        "Lire une erreur du compilateur",
        "Ce fichier ne compile pas. Lis le message ci-dessus : il te donne le fichier,\nla ligne, la colonne et la cause. Corrige, puis passe PAS_FINI a 0.",
        "En C, chaque instruction se termine par un point-virgule.",
    },
    {
        "intro3",
        "00_intro",
        "intro3.c",
        "Lire un rapport du sanitizer",
        "Le programme compile, et pourtant il explose. Le rapport AddressSanitizer\nau-dessus te dit quoi, ou, et de combien tu depasses.\nCorrige l'ecriture fautive.",
        "Un tableau de 4 cases a les indices 0, 1, 2 et 3. Pas 4.",
    },
    {
        "types1",
        "01_types",
        "types1.c",
        "La taille des entiers",
        "sizeof donne la taille d'un type en octets. Complete les valeurs attendues\npour que les verifications passent sur cette machine.",
        "Sur une machine 64 bits classique : char 1, short 2, int 4, long 8.",
    },
    {
        "types2",
        "01_types",
        "types2.c",
        "Le debordement d'entier",
        "Multiplier deux int assez grands deborde, et c'est un comportement indefini :\nUBSan arrete le programme. Le calcul doit se faire en long long.",
        "Il suffit qu'un seul des operandes soit deja un long long pour que la\nmultiplication entiere se fasse en long long : (long long)a * b.",
    },
    {
        "types3",
        "01_types",
        "types3.c",
        "Signe et non signe",
        "Comparer un int a un size_t force l'int a devenir non signe : -1 devient\nun nombre enorme. Corrige la fonction pour qu'elle reponde juste.",
        "Compare les deux valeurs dans le meme monde : convertis la taille en\nlong long, ou teste d'abord que l'indice n'est pas negatif.",
    },
    {
        "types4",
        "01_types",
        "types4.c",
        "Les flottants ne sont pas exacts",
        "0.1 + 0.2 ne vaut pas 0.3 en binaire. Ne compare jamais deux flottants\navec == : compare leur ecart a une tolerance.",
        "VERIFIE_PROCHE(obtenu, attendu, tolerance, message) existe deja.\nUne tolerance de 1e-9 convient ici.",
    },
    {
        "types5",
        "01_types",
        "types5.c",
        "Un char est un nombre",
        "En C, un caractere est un petit entier. 'A' vaut 65, et les lettres se\nsuivent. Ecris la conversion en majuscule sans table ni bibliotheque.",
        "'a' et 'A' sont separes d'un ecart constant : 'a' - 'A'.",
    },
    {
        "types6",
        "01_types",
        "types6.c",
        "La division entiere",
        "int / int donne un int : la partie decimale est jetee avant meme\nd'arriver au double. Convertis au bon moment.",
        "(double)a / b convertit a d'abord. (double)(a / b) convertit trop tard.",
    },
    {
        "flow1",
        "02_controle",
        "flow1.c",
        "if et else",
        "Complete la fonction pour qu'elle renvoie la mention correspondant a la note.\nL'ordre des tests compte.",
        "Teste d'abord le cas le plus restrictif. 16 est aussi superieur a 14.",
    },
    {
        "flow2",
        "02_controle",
        "flow2.c",
        "La boucle for",
        "Ecris la somme des entiers de 1 a n avec une boucle for.\nAttention aux bornes : de 1 a n inclus.",
        "for (int i = 1; i <= n; i++) fait bien n tours, de 1 a n.",
    },
    {
        "flow3",
        "02_controle",
        "flow3.c",
        "while et do-while",
        "Compte combien de fois il faut diviser n par 2 pour arriver a 1.\nLa boucle doit s'arreter : verifie ta condition.",
        "Tant que n est strictement superieur a 1, on divise et on compte.",
    },
    {
        "flow4",
        "02_controle",
        "flow4.c",
        "switch et la chute",
        "Un case sans break tombe dans le suivant. Ici c'est voulu pour les\nvoyelles, et une erreur pour le reste. Repare.",
        "Il manque un break apres le cas des chiffres.",
    },
    {
        "flow5",
        "02_controle",
        "flow5.c",
        "Les operateurs bit a bit",
        "Un entier est un paquet de bits. Ecris les trois operations de base :\nlire un bit, l'allumer, l'eteindre.",
        "Lire : (valeur >> position) & 1. Allumer : valeur | (1u << position).\nEteindre : valeur & ~(1u << position).",
    },
    {
        "fonc1",
        "03_fonctions",
        "fonc1.c",
        "Declarer avant d'utiliser",
        "En C, une fonction doit etre connue avant d'etre appelee.\nAjoute le prototype manquant en haut du fichier.",
        "Un prototype, c'est la signature suivie d'un point-virgule :\nint carre(int n);",
    },
    {
        "fonc2",
        "03_fonctions",
        "fonc2.c",
        "Le passage par valeur",
        "Une fonction C recoit une COPIE de l'argument. Modifier le parametre\nne change rien chez l'appelant. Fais renvoyer la valeur.",
        "Il faut renvoyer le resultat et l'assigner : compteur = incrementer(compteur);",
    },
    {
        "fonc3",
        "03_fonctions",
        "fonc3.c",
        "Modifier par pointeur",
        "Pour qu'une fonction modifie une variable de l'appelant, il faut lui\ndonner son adresse. Complete echanger.",
        "Un pointeur se dereference avec * : *a lit ou ecrit la valeur pointee.\nIl faut une variable temporaire.",
    },
    {
        "fonc4",
        "03_fonctions",
        "fonc4.c",
        "Un tableau en parametre",
        "Un tableau passe en parametre devient un pointeur : sa taille est perdue.\nIl faut la passer a cote.",
        "sizeof(tableau) dans la fonction donne la taille d'un pointeur, pas du\ntableau. Utilise le parametre taille.",
    },
    {
        "fonc5",
        "03_fonctions",
        "fonc5.c",
        "Un pointeur de fonction",
        "Une fonction a une adresse, donc on peut la ranger dans une variable\net la passer en parametre. Complete appliquer.",
        "Le type se lit de l'interieur : int (*operation)(int) est un pointeur\nvers une fonction qui prend un int et renvoie un int.",
    },
    {
        "ptr1",
        "04_pointeurs",
        "ptr1.c",
        "Adresse et dereferencement",
        "& donne l'adresse d'une variable, * lit ou ecrit la valeur a cette adresse.\nComplete la fonction pour qu'elle modifie la variable de l'appelant.",
        "Le parametre est un pointeur : *cible = valeur; ecrit dans la variable pointee.",
    },
    {
        "ptr2",
        "04_pointeurs",
        "ptr2.c",
        "Le pointeur nul",
        "Dereferencer NULL fait planter le programme. Une fonction qui recoit un\npointeur doit se demander s'il peut etre nul.",
        "Teste 'if (pointeur == NULL)' AVANT de faire *pointeur.",
    },
    {
        "ptr3",
        "04_pointeurs",
        "ptr3.c",
        "L'arithmetique de pointeur",
        "Ajouter 1 a un pointeur avance d'UN ELEMENT, pas d'un octet.\nParcours le tableau en deplacant un pointeur.",
        "pointeur + i pointe sur l'element i. *(debut + i) est la meme chose que debut[i].",
    },
    {
        "ptr4",
        "04_pointeurs",
        "ptr4.c",
        "const et pointeurs",
        "const int * : on ne peut pas modifier ce qui est pointe.\nint * const : on ne peut pas faire pointer ailleurs.\nCorrige la signature pour que la fonction promette de ne rien modifier.",
        "La signature doit etre : int maximum(const int *valeurs, size_t taille)",
    },
    {
        "ptr5",
        "04_pointeurs",
        "ptr5.c",
        "Un pointeur sur un pointeur",
        "Pour qu'une fonction change ou pointe un pointeur, il lui faut l'adresse\nde ce pointeur : un int **.",
        "*cible est le pointeur lui-meme, **cible est la valeur pointee.",
    },
    {
        "ptr6",
        "04_pointeurs",
        "ptr6.c",
        "Le pointeur qui pendouille",
        "Renvoyer l'adresse d'une variable locale est un piege : la variable\nn'existe plus au retour. AddressSanitizer le detecte.\nFais ecrire le resultat dans une zone fournie par l'appelant.",
        "Passe un tampon en parametre et ecris dedans, au lieu de renvoyer\nl'adresse d'un tableau local.",
    },
    {
        "ptr7",
        "04_pointeurs",
        "ptr7.c",
        "void* et la conversion",
        "void* est un pointeur sans type : il peut recevoir n'importe quelle adresse,\nmais il faut le reconvertir avant de s'en servir.",
        "Convertis le void* dans le bon type avant de dereferencer :\nconst int *entier = source;",
    },
    {
        "tab1",
        "05_tableaux",
        "tab1.c",
        "Indices et taille",
        "Un tableau de n cases va de l'indice 0 a n-1. Corrige la boucle qui\nrenverse le tableau.",
        "Pour renverser, echange l'element i avec l'element taille - 1 - i,\net arrete-toi au milieu.",
    },
    {
        "tab2",
        "05_tableaux",
        "tab2.c",
        "Sortir des bornes",
        "Cette boucle lit une case de trop. AddressSanitizer te dit exactement\nou et de combien. Corrige la condition d'arret.",
        "Avec i <= taille, le dernier tour lit valeurs[taille], qui n'existe pas.",
    },
    {
        "tab3",
        "05_tableaux",
        "tab3.c",
        "Un tableau n'est pas un pointeur",
        "sizeof d'un tableau donne sa taille totale. sizeof d'un pointeur donne\nla taille d'une adresse. Les deux ne sont pas le meme objet.",
        "sizeof(nombres) / sizeof(nombres[0]) donne le nombre de cases,\nmais seulement la ou le tableau est declare.",
    },
    {
        "tab4",
        "05_tableaux",
        "tab4.c",
        "Deux dimensions",
        "Un tableau 2D est range ligne par ligne, en continu. Complete l'acces\na la case (ligne, colonne).",
        "L'element (l, c) d'un tableau de largeur L est a l'indice l * L + c.",
    },
    {
        "tab5",
        "05_tableaux",
        "tab5.c",
        "Chercher dans un tableau",
        "Renvoie l'indice de la premiere occurrence, ou -1 si absente.\nAttention au type de retour quand rien n'est trouve.",
        "Renvoie un long long ou un int signe : un size_t ne peut pas valoir -1\nsans devenir un nombre enorme.",
    },
    {
        "tab6",
        "05_tableaux",
        "tab6.c",
        "Copier un tableau",
        "Un tableau ne se copie pas avec =. Il faut copier case par case,\nou utiliser memcpy.",
        "memcpy(destination, source, nombre_d_octets). Les octets, pas les cases :\ntaille * sizeof(int).",
    },
    {
        "str1",
        "06_chaines",
        "str1.c",
        "Le zero terminal",
        "Une chaine C, c'est des caracteres suivis d'un octet nul.\nLe tableau doit avoir la place pour ce zero.",
        "\"abc\" occupe 4 octets : 'a', 'b', 'c' et '\\\\0'.",
    },
    {
        "str2",
        "06_chaines",
        "str2.c",
        "Compter sans strlen",
        "Ecris ta propre version de strlen : avance jusqu'au zero terminal.",
        "while (texte[longueur] != '\\\\0') longueur++;",
    },
    {
        "str3",
        "06_chaines",
        "str3.c",
        "strcpy deborde",
        "strcpy ne connait pas la taille de la destination : il ecrit jusqu'au\nzero de la source. Ici ca deborde, et ASan le voit.\nUtilise snprintf, qui prend la taille.",
        "snprintf(destination, sizeof destination, \"%s\", source) ne depasse jamais.",
    },
    {
        "str4",
        "06_chaines",
        "str4.c",
        "Le piege de strncpy",
        "strncpy ne met PAS de zero terminal si la source remplit exactement la\ndestination. Corrige pour garantir une chaine valide.",
        "Apres strncpy, force le dernier octet a zero :\ndestination[taille - 1] = '\\\\0';",
    },
    {
        "str5",
        "06_chaines",
        "str5.c",
        "Comparer deux chaines",
        "== compare deux adresses, pas deux contenus. Pour comparer le texte,\nc'est strcmp, qui renvoie 0 quand c'est egal.",
        "strcmp(a, b) == 0 signifie 'les deux chaines sont identiques'.",
    },
    {
        "str6",
        "06_chaines",
        "str6.c",
        "Construire sans deborder",
        "snprintf renvoie la longueur qu'il AURAIT ecrite. C'est ce qui permet\nde detecter une troncature.",
        "Si la valeur renvoyee est superieure ou egale a la taille du tampon,\nle texte a ete tronque.",
    },
    {
        "str7",
        "06_chaines",
        "str7.c",
        "Parcourir des mots",
        "Compte les mots d'une phrase sans rien allouer : un mot commence quand\non passe d'un espace a autre chose.",
        "Garde un drapeau 'dans_un_mot'. Il passe a 1 au debut d'un mot et\nretombe a 0 sur un espace.",
    },
    {
        "mem1",
        "07_memoire",
        "mem1.c",
        "malloc et free",
        "malloc reserve des octets et renvoie leur adresse, ou NULL si ca rate.\nfree les rend. Complete l'allocation.",
        "Pour n entiers : malloc(n * sizeof(int)). Et teste le retour contre NULL.",
    },
    {
        "mem2",
        "07_memoire",
        "mem2.c",
        "La fuite",
        "Ce programme alloue et oublie de rendre. LeakSanitizer n'existe pas sur\nmacOS : clings compte les blocs a la main avec suivi_malloc et suivi_free.\nRends ce que tu prends.",
        "Il manque un suivi_free avant le return, sur le chemin d'erreur aussi.",
    },
    {
        "mem3",
        "07_memoire",
        "mem3.c",
        "Le double free",
        "Rendre deux fois le meme bloc corrompt l'allocateur. ASan l'attrape.\nUn seul free par malloc.",
        "Enleve le free en trop. Mettre le pointeur a NULL apres free est une\nbonne habitude : free(NULL) ne fait rien.",
    },
    {
        "mem4",
        "07_memoire",
        "mem4.c",
        "Utiliser apres liberation",
        "Lire un bloc deja rendu est un comportement indefini. ASan appelle ca\nun heap-use-after-free. Reordonne le code.",
        "Fais toutes tes lectures AVANT le free.",
    },
    {
        "mem5",
        "07_memoire",
        "mem5.c",
        "realloc",
        "realloc peut deplacer le bloc : il faut reaffecter le pointeur, et ne\njamais ecraser l'ancien avant d'avoir verifie le retour.",
        "int *agrandi = suivi_realloc(bloc, nouvelle_taille);\nif (agrandi == NULL) { ... } else { bloc = agrandi; }",
    },
    {
        "mem6",
        "07_memoire",
        "mem6.c",
        "calloc et la memoire sale",
        "malloc ne remet rien a zero : le bloc contient ce qui trainait.\ncalloc, si. Choisis le bon selon ce que tu fais ensuite.",
        "calloc(nombre, taille) alloue et remplit de zeros.",
    },
    {
        "mem7",
        "07_memoire",
        "mem7.c",
        "Un tableau qui grandit",
        "Ecris la fonction qui ajoute un element, en doublant la capacite quand\nle tableau est plein. C'est le coeur de tout vecteur dynamique.",
        "Quand taille == capacite, double la capacite (minimum 1), realloc,\npuis ecris l'element et incremente taille.",
    },
};

const int CATALOGUE_TAILLE = (int)(sizeof CATALOGUE / sizeof CATALOGUE[0]);

const Question QUESTIONS[] = {
    {
        "00_intro",
        "Que fait exactement AddressSanitizer ?",
        {
            "Il corrige les erreurs memoire automatiquement",
            "Il ajoute des verifications autour de chaque acces memoire, a l'execution",
            "Il analyse le code source sans le lancer",
            "Il empeche le programme de compiler s'il y a un bug",
        },
        1,
        "ASan instrumente le programme a la compilation : chaque lecture et chaque\necriture verifie une carte des zones valides. C'est une verification a\nl'EXECUTION, donc elle ne voit que les chemins reellement parcourus.",
    },
    {
        "00_intro",
        "Un tableau declare 'int t[4]' a quels indices valides ?",
        {
            "0 a 4",
            "1 a 4",
            "0 a 3",
            "1 a 3",
        },
        2,
        "Quatre cases, numerotees a partir de zero : 0, 1, 2, 3. t[4] est hors\nbornes, et c'est la faute la plus frequente du langage.",
    },
    {
        "01_types",
        "Que vaut 7 / 2 en C, avec deux int ?",
        {
            "3.5",
            "3",
            "4",
            "cela depend du compilateur",
        },
        1,
        "La division de deux entiers est une division entiere : la partie decimale\nest jetee, pas arrondie. Pour obtenir 3.5 il faut convertir AVANT :\n(double)7 / 2.",
    },
    {
        "01_types",
        "Pourquoi 'if (-1 < taille)' peut etre faux quand taille est un size_t ?",
        {
            "Parce que size_t est plus petit qu'un int",
            "Parce que -1 est converti en un tres grand nombre non signe",
            "Parce que la comparaison est indefinie",
            "Parce que le compilateur inverse l'operateur",
        },
        1,
        "Quand on compare un type signe et un type non signe de meme rang ou plus\ngrand, le signe est converti vers le non signe. -1 devient 18446744073709551615.\nC'est un bug classique, et le compilateur le signale avec -Wsign-compare.",
    },
    {
        "01_types",
        "Le debordement d'un int signe est :",
        {
            "Un enveloppement (wrap) garanti",
            "Un comportement indefini",
            "Une erreur de compilation",
            "Une exception a l'execution",
        },
        1,
        "Le debordement signe est un comportement indefini : le compilateur a le\ndroit de supposer qu'il n'arrive jamais et d'optimiser en consequence.\nLe debordement NON signe, lui, est defini et enveloppe.",
    },
    {
        "02_controle",
        "Que fait un 'case' sans 'break' dans un switch ?",
        {
            "Il sort du switch",
            "Il tombe dans le case suivant",
            "C'est une erreur de compilation",
            "Il repart au debut du switch",
        },
        1,
        "C'est la chute (fallthrough). Parfois voulue pour regrouper des cas,\nsouvent un oubli. Les compilateurs modernes savent le signaler avec\n-Wimplicit-fallthrough.",
    },
    {
        "02_controle",
        "Que vaut (1u << 3) ?",
        {
            "3",
            "6",
            "8",
            "16",
        },
        2,
        "Decaler 1 de n positions vers la gauche revient a multiplier par 2 puissance n.\n1 << 3 vaut 8. C'est la base de tous les masques de bits.",
    },
    {
        "03_fonctions",
        "Une fonction C recoit ses arguments :",
        {
            "Par reference",
            "Par copie",
            "Par reference si c'est un tableau",
            "Cela depend du compilateur",
        },
        1,
        "Toujours par copie. Un pointeur est copie lui aussi : c'est l'ADRESSE qui\nest dupliquee, ce qui permet quand meme de modifier ce qu'elle designe.\nUn tableau, lui, se convertit en pointeur avant d'etre copie.",
    },
    {
        "03_fonctions",
        "Que donne sizeof(t) dans 'void f(int t[10])' ?",
        {
            "40",
            "10",
            "la taille d'un pointeur",
            "erreur de compilation",
        },
        2,
        "Le parametre n'est PAS un tableau : le [10] est decoratif, le compilateur\nle transforme en int*. sizeof donne donc la taille d'une adresse.\nC'est pour cela qu'on passe toujours la taille a cote.",
    },
    {
        "04_pointeurs",
        "Que fait 'pointeur + 1' sur un int* ?",
        {
            "Avance d'un octet",
            "Avance de 4 octets sur une machine ou int fait 4",
            "Avance d'un bit",
            "Provoque une erreur",
        },
        1,
        "L'arithmetique de pointeur compte en ELEMENTS, pas en octets. Le compilateur\nmultiplie par sizeof du type pointe. C'est ce qui rend p[i] equivalent a\n*(p + i).",
    },
    {
        "04_pointeurs",
        "Renvoyer l'adresse d'une variable locale, c'est :",
        {
            "Legal et pratique",
            "Legal mais lent",
            "Un pointeur vers une zone qui n'existe plus",
            "Interdit par le compilateur",
        },
        2,
        "La variable vit dans le cadre de pile de la fonction, detruit au retour.\nL'adresse reste valide syntaxiquement mais ne designe plus rien :\nc'est un pointeur pendouillant. ASan le detecte en mode\ndetect_stack_use_after_return.",
    },
    {
        "04_pointeurs",
        "A quoi sert 'const' dans 'const int *p' ?",
        {
            "p ne peut pas changer de cible",
            "on ne peut pas modifier *p",
            "les deux",
            "aucun des deux, c'est decoratif",
        },
        1,
        "const int *p : la VALEUR pointee est en lecture seule, mais p peut pointer\nailleurs. int * const p : l'inverse. Lis de droite a gauche a partir du nom.",
    },
    {
        "05_tableaux",
        "sizeof(t) / sizeof(t[0]) donne le nombre de cases :",
        {
            "toujours",
            "seulement la ou le tableau est declare",
            "seulement pour les tableaux de char",
            "jamais, c'est une legende",
        },
        1,
        "Des que le tableau est passe a une fonction, il devient un pointeur et\nl'astuce donne un resultat faux, souvent 1 ou 2. Elle ne vaut que dans\nla portee ou le tableau est declare.",
    },
    {
        "05_tableaux",
        "Comment copier un tableau de 4 int ?",
        {
            "copie = source;",
            "memcpy(copie, source, 4);",
            "memcpy(copie, source, sizeof source);",
            "copie[] = source[];",
        },
        2,
        "memcpy compte en OCTETS. Passer 4 ne copie que le premier int.\nsizeof source donne bien 16 sur une machine ou int fait 4.",
    },
    {
        "06_chaines",
        "Combien d'octets occupe la chaine \"abc\" ?",
        {
            "3",
            "4",
            "6",
            "cela depend de l'encodage",
        },
        1,
        "Trois caracteres plus l'octet nul de fin. Oublier de compter ce zero est\nla cause numero un des debordements de tampon en C.",
    },
    {
        "06_chaines",
        "Quel est le piege de strncpy ?",
        {
            "Elle est plus lente que strcpy",
            "Elle n'ecrit pas de zero terminal si la source remplit la destination",
            "Elle refuse les chaines vides",
            "Elle alloue de la memoire",
        },
        1,
        "strncpy remplit exactement n octets. Si la source fait n caracteres ou plus,\nil n'y a pas de place pour le zero, et la 'chaine' obtenue n'en est pas une.\nEn pratique, prefere snprintf.",
    },
    {
        "06_chaines",
        "Que compare 'if (a == b)' quand a et b sont des char* ?",
        {
            "Le contenu des chaines",
            "Les deux adresses",
            "La longueur des chaines",
            "Le premier caractere",
        },
        1,
        "Ce sont deux pointeurs : on compare des adresses. Pour comparer le contenu,\nc'est strcmp, qui renvoie 0 quand les chaines sont identiques.",
    },
    {
        "07_memoire",
        "Que contient un bloc juste renvoye par malloc ?",
        {
            "Des zeros",
            "Ce qui trainait a cet endroit de la memoire",
            "Des valeurs aleatoires garanties",
            "Le contenu du bloc precedemment libere",
        },
        1,
        "malloc ne promet rien sur le contenu. Lire un bloc non initialise est un\ncomportement indefini. calloc, lui, garantit des zeros, au prix d'un\nremplissage.",
    },
    {
        "07_memoire",
        "Que faire si realloc renvoie NULL ?",
        {
            "Rien, le bloc a ete libere",
            "Le bloc d'origine est toujours valide et doit etre libere",
            "Recommencer immediatement",
            "Le programme s'arrete tout seul",
        },
        1,
        "En cas d'echec, realloc ne touche pas au bloc d'origine. Ecrire\n'bloc = realloc(bloc, n)' perd donc l'ancienne adresse et fuit :\nil faut passer par une variable temporaire.",
    },
    {
        "07_memoire",
        "Pourquoi mettre un pointeur a NULL apres free ?",
        {
            "Pour liberer plus vite",
            "Pour que free soit appele deux fois sans risque",
            "Parce que le compilateur l'exige",
            "Pour economiser de la memoire",
        },
        1,
        "free(NULL) est defini et ne fait rien. Mettre le pointeur a NULL apres\nliberation transforme donc un double free en operation inoffensive, et\nrend les utilisations apres liberation plus faciles a reperer.",
    },
    {
        "07_memoire",
        "Pourquoi doubler la capacite d'un tableau dynamique ?",
        {
            "Pour economiser la memoire",
            "Pour que le cout moyen d'un ajout reste constant",
            "Parce que realloc l'exige",
            "C'est arbitraire",
        },
        1,
        "En doublant, le nombre de reallocations pour n ajouts est proportionnel a\nlog n, et le cout total des copies reste proportionnel a n : chaque ajout\ncoute donc un temps constant en moyenne. Agrandir de 1 a chaque fois\ndonnerait un cout total en n au carre.",
    },
};

const int QUESTIONS_TAILLE = (int)(sizeof QUESTIONS / sizeof QUESTIONS[0]);
