<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Demos.Pure</RootNamespace>
    <AssemblyName>demos-pure</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../godot/weakrefs/WeakCache.cs" />
    <Compile Include="../godot/weakrefs/WeakEventBus.cs" />
  </ItemGroup>
</Project>
