#include "catalogue.hpp"

namespace {

const std::vector<Exercice> EXERCICES = {
    {
        "intro1",
        "00_intro",
        "intro1.cpp",
        "Comment ca marche",
        "Rien a corriger : ce fichier tourne deja.\nOuvre-le, passe PAS_FINI a false, sauvegarde.",
        "La ligne est 'const bool PAS_FINI = true;'. Remplace true par false.",
        "c++20",
    },
    {
        "intro2",
        "00_intro",
        "intro2.cpp",
        "Lire une erreur du compilateur",
        "Ce fichier ne compile pas. Lis le message ci-dessus : fichier, ligne,\ncolonne, cause. Corrige, puis passe PAS_FINI a false.",
        "En C++, chaque instruction se termine par un point-virgule.",
        "c++20",
    },
    {
        "intro3",
        "00_intro",
        "intro3.cpp",
        "Lire une erreur de template",
        "Le compilateur va cracher pres de trois cents lignes et une vingtaine\nd'erreurs. Ne les lis pas dans l'ordre : la PREMIERE 'error:' est la cause,\ntout le reste en decoule. Cherche ensuite 'requested here' pour retrouver\nTA ligne. Le comparateur ne prend pas le bon type.",
        "std::sort sur un vector<string> passe des string au comparateur,\npas des int.",
        "c++20",
    },
    {
        "base1",
        "01_bases",
        "base1.cpp",
        "auto copie par defaut",
        "'auto x : conteneur' fait une COPIE a chaque tour. La Sonde compte les\ncopies : fais tomber le compteur a zero.",
        "Boucle par reference constante : 'for (const auto &sonde : sondes)'.",
        "c++20",
    },
    {
        "base2",
        "01_bases",
        "base2.cpp",
        "Les references",
        "Une reference est un autre nom pour la meme variable : pas de copie,\npas de pointeur, et elle ne peut jamais etre nulle ni changer de cible.",
        "'int &lien = valeur;' fait de lien un alias. Ecrire dans lien ecrit\ndans valeur.",
        "c++20",
    },
    {
        "base3",
        "01_bases",
        "base3.cpp",
        "const et constexpr",
        "'const' promet de ne pas modifier. 'constexpr' calcule a la compilation.\nRends la fonction utilisable dans un static_assert.",
        "Marque la fonction constexpr. Une fonction constexpr peut aussi etre\nappelee normalement a l'execution.",
        "c++20",
    },
    {
        "base4",
        "01_bases",
        "base4.cpp",
        "Le piege des accolades",
        "std::vector<int> v(3, 5) fait trois cases valant 5.\nstd::vector<int> v{3, 5} fait DEUX cases valant 3 et 5.\nLes accolades preferent toujours la liste d'initialisation.",
        "Utilise des parentheses pour appeler le constructeur (nombre, valeur).",
        "c++20",
    },
    {
        "base5",
        "01_bases",
        "base5.cpp",
        "Liaison structurée",
        "Une liaison structuree decompose un agregat en variables nommees.\nUtilise-la pour parcourir la map sans passer par .first et .second.",
        "for (const auto &[cle, valeur] : scores) { ... }",
        "c++20",
    },
    {
        "base6",
        "01_bases",
        "base6.cpp",
        "nullptr, pas NULL",
        "NULL est un entier deguise : il peut choisir la mauvaise surcharge.\nnullptr a son propre type et ne se trompe jamais.",
        "Passe nullptr au lieu de 0 ou NULL.",
        "c++20",
    },
    {
        "val1",
        "02_valeurs",
        "val1.cpp",
        "Passer par valeur copie",
        "Ce parametre est pris par valeur : chaque appel copie l'objet entier.\nLa Sonde le compte. Fais tomber le compteur a zero.",
        "Prends le parametre par reference constante : const verif::Sonde &",
        "c++20",
    },
    {
        "val2",
        "02_valeurs",
        "val2.cpp",
        "Le retour par valeur est gratuit",
        "Renvoyer un objet local ne le copie pas : le compilateur le construit\ndirectement chez l'appelant. C'est l'elision de copie, obligatoire\ndepuis C++17. Ne l'empeche pas avec un std::move inutile.",
        "Un 'return std::move(local)' EMPECHE l'elision et force un deplacement.\nEcris simplement 'return local;'.",
        "c++20",
    },
    {
        "val3",
        "02_valeurs",
        "val3.cpp",
        "std::move ne deplace rien",
        "std::move ne fait AUCUN travail : c'est une conversion de type qui dit\n'tu peux me piller'. C'est le constructeur de deplacement qui agit.\nUtilise-le pour eviter la copie dans le vecteur.",
        "std::move(sonde) transforme la lvalue en rvalue, ce qui selectionne\nla surcharge de deplacement de push_back.",
        "c++20",
    },
    {
        "val4",
        "02_valeurs",
        "val4.cpp",
        "Le parametre puits",
        "Quand une fonction STOCKE son argument, le prendre par valeur puis le\ndeplacer est la bonne recette : un seul deplacement depuis une rvalue.",
        "Prends le parametre par valeur, puis 'stock.push_back(std::move(sonde));'",
        "c++20",
    },
    {
        "val5",
        "02_valeurs",
        "val5.cpp",
        "Une reference qui survit a sa cible",
        "Cette fonction renvoie une reference vers une variable locale : elle ne\ndesigne plus rien au retour. AddressSanitizer le voit.\nRenvoie par valeur.",
        "Change le type de retour en 'std::string' au lieu de 'const std::string &'.",
        "c++20",
    },
    {
        "raii1",
        "03_raii",
        "raii1.cpp",
        "Le destructeur, a la sortie de portee",
        "Un objet local est detruit a la fermeture de l'accolade, quoi qu'il arrive.\nC'est toute la mecanique de RAII. Ouvre une portee pour que ce soit vrai.",
        "Entoure la creation de la sonde par une paire d'accolades : { ... }",
        "c++20",
    },
    {
        "raii2",
        "03_raii",
        "raii2.cpp",
        "new sans delete sur le chemin d'erreur",
        "Ce code libere bien... sauf quand il sort tot. La Sonde compte les\nconstructions et les destructions : elles doivent s'equilibrer.\nUtilise un unique_ptr et le probleme disparait.",
        "std::make_unique<verif::Sonde>(valeur) libere tout seul, y compris sur\nun return anticipe.",
        "c++20",
    },
    {
        "raii3",
        "03_raii",
        "raii3.cpp",
        "unique_ptr ne se copie pas",
        "unique_ptr represente une propriete EXCLUSIVE : il ne se copie pas,\nil se deplace. C'est verifie a la compilation.",
        "std::move(premier) transfere la propriete. Apres, premier vaut nullptr.",
        "c++20",
    },
    {
        "raii4",
        "03_raii",
        "raii4.cpp",
        "shared_ptr et son compteur",
        "shared_ptr partage la propriete : il compte les proprietaires, et libere\nquand le compteur tombe a zero. Ce compteur est ATOMIQUE, donc chaque\ncopie coute une operation synchronisee.",
        "use_count() donne le nombre de proprietaires. Une copie l'incremente,\nune sortie de portee le decremente.",
        "c++20",
    },
    {
        "raii5",
        "03_raii",
        "raii5.cpp",
        "Ecrire son garde de portee",
        "RAII n'est pas reserve a la memoire : tout ce qui s'ouvre et se ferme\nen profite. Ecris un garde qui execute une action a la destruction.",
        "Stocke l'action dans un membre, et appelle-la dans le destructeur.",
        "c++20",
    },
    {
        "raii6",
        "03_raii",
        "raii6.cpp",
        "L'ordre de destruction",
        "Les objets sont detruits dans l'ordre INVERSE de leur construction.\nComplete la trace attendue.",
        "Construits a, b, c : detruits c, b, a.",
        "c++20",
    },
    {
        "rz1",
        "04_regle_zero",
        "rz1.cpp",
        "La regle de zero",
        "Cette classe ne gere aucune ressource brute : ses membres savent deja se\ncopier, se deplacer et se detruire. N'ecris donc RIEN.",
        "Supprime le destructeur vide : il empeche le compilateur de generer\nles operations de deplacement.",
        "c++20",
    },
    {
        "rz2",
        "04_regle_zero",
        "rz2.cpp",
        "La regle de cinq",
        "Des qu'on ecrit un destructeur, le compilateur cesse de generer les\noperations de DEPLACEMENT : tout retombe sur la copie.\nRedeclare-les en '= default'.",
        "Ajoute :\n  Tampon(Tampon &&) noexcept = default;\n  Tampon &operator=(Tampon &&) noexcept = default;",
        "c++20",
    },
    {
        "rz3",
        "04_regle_zero",
        "rz3.cpp",
        "Ecrire le deplacement a la main",
        "Quand on possede une ressource brute, il faut ecrire soi-meme le\ndeplacement : voler le pointeur, et laisser la source dans un etat\nvalide et destructible.",
        "Copie le pointeur et la taille, puis mets ceux de la source a nullptr\net 0. Sinon les deux objets libereront le meme bloc.",
        "c++20",
    },
    {
        "rz4",
        "04_regle_zero",
        "rz4.cpp",
        "Interdire la copie",
        "Certaines classes n'ont aucun sens copiees : un verrou, un fichier,\nune connexion. '= delete' l'interdit a la COMPILATION.",
        "Ajoute : Ressource(const Ressource &) = delete;\net l'operateur d'affectation correspondant.",
        "c++20",
    },
    {
        "rz5",
        "04_regle_zero",
        "rz5.cpp",
        "La copie superficielle",
        "Cette classe possede un bloc brut et laisse le compilateur generer la\ncopie : les deux objets pointent sur le MEME bloc, et le liberent tous\nles deux. ASan appelle ca un double-free. Ecris une copie profonde.",
        "Le constructeur de copie doit allouer son propre bloc et recopier le\ncontenu, pas recopier le pointeur.",
        "c++20",
    },
    {
        "cont1",
        "05_conteneurs",
        "cont1.cpp",
        "Taille et capacite",
        "size() est le nombre d'elements, capacity() la place reservee. Chaque\ndepassement de capacite realloue et deplace tout. reserve() evite ca\nquand on connait le nombre final.",
        "Appelle sondes.reserve(100) avant la boucle.",
        "c++20",
    },
    {
        "cont2",
        "05_conteneurs",
        "cont2.cpp",
        "L'invalidation",
        "push_back peut reallouer : toute reference, tout pointeur et tout\niterateur vers l'interieur devient invalide. ASan appelle ca un\nheap-use-after-free. Relis la valeur APRES l'ajout.",
        "Ne garde pas de pointeur a travers un push_back : indexe le vecteur\napres coup, avec nombres[0].",
        "c++20",
    },
    {
        "cont3",
        "05_conteneurs",
        "cont3.cpp",
        "emplace_back construit sur place",
        "push_back prend un objet deja fait et le copie ou le deplace.\nemplace_back recoit les arguments et construit directement dans le\nconteneur : zero copie, zero deplacement.",
        "sondes.emplace_back(i) construit la Sonde dans le vecteur.",
        "c++20",
    },
    {
        "cont4",
        "05_conteneurs",
        "cont4.cpp",
        "std::string et la petite chaine",
        "Une std::string courte ne fait aucune allocation : elle range ses octets\ndans l'objet lui-meme. C'est l'optimisation des petites chaines.\nAu-dela d'une quinzaine de caracteres, elle passe sur le tas.",
        "Une chaine de 3 caracteres tient dans l'objet ; une de 200, non.\nCompare data() a l'adresse de l'objet.",
        "c++20",
    },
    {
        "cont5",
        "05_conteneurs",
        "cont5.cpp",
        "map ou unordered_map",
        "std::map est un arbre trie : parcours ordonne, recherche en log(n).\nstd::unordered_map est une table de hachage : parcours en desordre,\nrecherche en temps constant moyen. Choisis selon ce dont tu as besoin.",
        "Ici on veut un parcours dans l'ordre des cles : c'est std::map.",
        "c++20",
    },
    {
        "cont6",
        "05_conteneurs",
        "cont6.cpp",
        "Supprimer pendant un parcours",
        "Effacer dans une boucle indexee saute des elements et invalide les\niterateurs. std::erase fait le travail en une passe, correctement.",
        "std::erase_if(nombres, [](int n) { return n % 2 == 0; });",
        "c++20",
    },
    {
        "algo1",
        "06_algos",
        "algo1.cpp",
        "Trier avec un comparateur",
        "std::sort prend un predicat 'a passe avant b'. Il doit etre un ordre\nSTRICT : comparer avec <= au lieu de < casse l'algorithme.",
        "Le comparateur renvoie true si a doit passer avant b. Pour un tri\ndecroissant : a > b.",
        "c++20",
    },
    {
        "algo2",
        "06_algos",
        "algo2.cpp",
        "Une capture qui survit a sa cible",
        "Cette lambda capture une variable locale PAR REFERENCE et sort de la\nfonction : la reference ne designe plus rien. ASan le detecte.\nCapture par valeur.",
        "Remplace [&valeur] par [valeur] : la lambda garde alors sa propre copie.",
        "c++20",
    },
    {
        "algo3",
        "06_algos",
        "algo3.cpp",
        "Chercher et accumuler",
        "find_if renvoie un iterateur sur le premier element qui satisfait le\npredicat, ou end() s'il n'y en a pas. Comparer a end() est obligatoire\navant de dereferencer.",
        "auto trouve = std::find_if(...); if (trouve != v.end()) { ... }",
        "c++20",
    },
    {
        "algo4",
        "06_algos",
        "algo4.cpp",
        "Les vues sont paresseuses",
        "Une vue de ranges ne calcule rien tant qu'on ne la parcourt pas, et ne\ncopie jamais le conteneur. Chaine un filtre et une transformation.",
        "nombres | std::views::filter(...) | std::views::transform(...)",
        "c++20",
    },
    {
        "algo5",
        "06_algos",
        "algo5.cpp",
        "std::span, une vue sur des elements",
        "std::span est un pointeur PLUS une taille : il ne possede rien, ne copie\nrien, et remplace le couple (pointeur, taille) du C.",
        "Change le parametre en std::span<const int>. Un vector et un tableau\nbrut s'y convertissent tous les deux.",
        "c++20",
    },
    {
        "tmpl1",
        "07_templates",
        "tmpl1.cpp",
        "Un template remplace les surcharges",
        "Deux surcharges ecrites a la main, et le troisieme type ne compile pas.\nEcris la recette une seule fois, pour tous les types.",
        "template <typename T> T maximum(const T &a, const T &b). Le T se deduit\ndes arguments : rien a annoter a l'appel.",
        "c++20",
    },
    {
        "tmpl2",
        "07_templates",
        "tmpl2.cpp",
        "Template de classe et taille dans le type",
        "La pile est figee a quatre int. Rends-la generique sur le type ET sur la\ncapacite, sans allouer quoi que ce soit.",
        "template <typename T, std::size_t N>. N est un parametre non-type :\nune valeur connue a la compilation, utilisable comme taille de tableau.",
        "c++20",
    },
    {
        "tmpl3",
        "07_templates",
        "tmpl3.cpp",
        "if constexpr",
        "Un if ordinaire compile SES DEUX branches, meme celle qui ne sera jamais\nprise. Pour un int, valeur.size() n'existe pas.",
        "if constexpr (std::is_integral_v<T>) : la branche non prise est\nsupprimee avant d'etre analysee.",
        "c++20",
    },
    {
        "tmpl4",
        "07_templates",
        "tmpl4.cpp",
        "Les concepts",
        "Deux templates de meme signature, c'est une redefinition. Contrains-les :\nune surcharge pour les entiers, une pour les flottants.",
        "template <std::integral T> et template <std::floating_point T>,\ndepuis <concepts>. La surcharge la plus contrainte gagne.",
        "c++20",
    },
    {
        "tmpl5",
        "07_templates",
        "tmpl5.cpp",
        "Variadique et expression de repli",
        "Une surcharge par nombre d'arguments, ca ne tient pas. Ecris une seule\nfonction qui en accepte autant qu'on veut, de n'importe quel type.",
        "template <typename... T> auto somme(T... valeurs), et le repli\n(valeurs + ... + 0), qui donne 0 quand il n'y a aucun argument.",
        "c++20",
    },
    {
        "tmpl6",
        "07_templates",
        "tmpl6.cpp",
        "Le transfert parfait",
        "Le parametre pris par valeur copie une fois de plus que necessaire.\nLa Sonde compte : fais tomber le compteur.",
        "T &&valeur dans un template deduit n'est pas une reference sur rvalue,\nc'est une reference universelle. Rends-la avec std::forward<T>(valeur).",
        "c++20",
    },
    {
        "err1",
        "08_erreurs",
        "err1.cpp",
        "Une exception traverse un new",
        "Quand l'exception part, le delete n'est jamais atteint et la Sonde n'est\njamais detruite. Le compteur le prouve.",
        "std::make_unique : le destructeur du unique_ptr est appele pendant le\nderoulement de la pile, exception ou pas.",
        "c++20",
    },
    {
        "err2",
        "08_erreurs",
        "err2.cpp",
        "noexcept, ou vector copie",
        "Le vector realloue et COPIE a chaque fois, alors que le type sait se\ndeplacer. Il manque une promesse.",
        "std::move_if_noexcept : sans noexcept sur le constructeur de\ndeplacement, et si le type est copiable, vector prefere copier pour\ngarder la garantie forte.",
        "c++20",
    },
    {
        "err3",
        "08_erreurs",
        "err3.cpp",
        "optional plutot que -1",
        "Renvoyer -1 pour dire 'pas trouve' oblige l'appelant a connaitre la\nconvention, et rien ne l'y force. Dis-le dans le type.",
        "std::optional<std::size_t>, et std::nullopt quand rien ne correspond.\nAucune allocation : la valeur est logee dans l'optional lui-meme.",
        "c++20",
    },
    {
        "err4",
        "08_erreurs",
        "err4.cpp",
        "expected porte la cause",
        "La division ne verifie rien : UBSan arrete le programme sur 10 / 0.\nRenvoie une valeur OU une raison.",
        "std::unexpected(std::string(\"division par zero\")) pour le cas d'erreur.\nexpected<int, std::string> accepte les deux, sans exception ni allocation\nsur le chemin normal.",
        "c++23",
    },
    {
        "err5",
        "08_erreurs",
        "err5.cpp",
        "Attraper par reference",
        "Attrapee par valeur, l'exception est decoupee : il ne reste que la partie\nde base, et what() ne dit plus rien d'utile.",
        "catch (const std::exception &erreur). Une exception s'attrape toujours\npar reference constante.",
        "c++20",
    },
    {
        "lay1",
        "09_layout",
        "lay1.cpp",
        "Reordonner les membres",
        "Les memes membres, le meme code, deux tailles differentes selon l'ordre.\nReordonne sans rien supprimer : les verifications relisent tout.",
        "Du membre le plus exigeant au moins exigeant. alignof te dit\nl'exigence de chacun, et la solution le fige dans un static_assert.",
        "c++20",
    },
    {
        "lay2",
        "09_layout",
        "lay2.cpp",
        "[[no_unique_address]]",
        "La politique de comparaison n'a aucun etat, et pourtant elle occupe de\nla place : un membre distinct doit avoir une adresse distincte.",
        "[[no_unique_address]] leve cette obligation quand le membre est vide :\nil peut alors partager l'adresse du suivant.",
        "c++20",
    },
    {
        "lay3",
        "09_layout",
        "lay3.cpp",
        "Le faux partage",
        "Deux compteurs voisins, deux fils qui ecrivent chacun le sien : ils se\nvolent la meme ligne de cache a chaque tour. Ecarte-les.",
        "alignas sur le membre force le suivant a commencer une ligne plus loin.\nLa verification compare la distance entre les deux adresses.",
        "c++20",
    },
    {
        "lay4",
        "09_layout",
        "lay4.cpp",
        "memcpy et is_trivially_copyable",
        "Copier les octets d'un objet qui possede une ressource fabrique deux\nproprietaires du meme bloc. Interdis-le a la compilation.",
        "static_assert(std::is_trivially_copyable_v<T>) dans la fonction qui\ncopie les octets, et une affectation ordinaire pour le type qui possede.",
        "c++20",
    },
    {
        "lay5",
        "09_layout",
        "lay5.cpp",
        "Tableau de structures, structure de tableaux",
        "La boucle ne lit qu'un champ sur quatre, et traverse quand meme les\nquatre. Transpose la disposition, et compte les octets.",
        "Un vecteur par champ au lieu d'un vecteur de structures : la boucle\nchaude ne traverse plus que le tableau dont elle a besoin.",
        "c++20",
    },
    {
        "lay6",
        "09_layout",
        "lay6.cpp",
        "Aligner une allocation",
        "Le type demande un alignement de 32 octets ; l'allocation passe par un\nchemin qui l'ignore, et l'adresse obtenue ne le respecte pas.",
        "Depuis C++17, new connait l'alignement du type et appelle la surcharge\nalignee. Encore faut-il lui demander le type, pas des octets.",
        "c++20",
    },
    {
        "poly1",
        "10_polymorphisme",
        "poly1.cpp",
        "virtual oublie",
        "A travers un pointeur de base, c'est la fonction de la base qui est\nappelee : sans virtual, le choix se fait sur le type ECRIT, pas sur le\ntype reel.",
        "virtual dans la base, override dans chaque derivee.",
        "c++20",
    },
    {
        "poly2",
        "10_polymorphisme",
        "poly2.cpp",
        "Le destructeur virtuel",
        "delete a travers un pointeur de base n'appelle que le destructeur de la\nbase. Le compteur de la Sonde montre ce qui n'a pas ete detruit.",
        "Une classe destinee a etre heritee et detruite par la base a un\ndestructeur virtuel. C'est la seule ligne qui manque.",
        "c++20",
    },
    {
        "poly3",
        "10_polymorphisme",
        "poly3.cpp",
        "override attrape la signature qui derape",
        "La derivee croit redefinir la methode de la base. Un const de trop, et\nelle en ajoute une nouvelle a cote, sans un mot du compilateur.",
        "Mets override sur toutes les redefinitions : le silence devient une\nerreur de compilation, et il ne reste plus qu'a accorder les signatures.",
        "c++20",
    },
    {
        "poly4",
        "10_polymorphisme",
        "poly4.cpp",
        "Le decoupage",
        "Un vector<Base> stocke des Base, et rien d'autre. Y ranger une derivee\nla tronque a sa partie de base, silencieusement.",
        "Le polymorphisme ne marche qu'a travers un pointeur ou une reference :\nvector<unique_ptr<Base>>.",
        "c++20",
    },
    {
        "poly5",
        "10_polymorphisme",
        "poly5.cpp",
        "CRTP, le polymorphisme sans table",
        "La meme hierarchie sans une seule fonction virtuelle : la base connait\nsa derivee par son parametre de template.",
        "template <typename Derivee> struct Base, et un appel qui passe par\nstatic_cast<Derivee *>(this). Le sizeof le prouve : plus de pointeur\nde table dans l'objet.",
        "c++20",
    },
    {
        "poly6",
        "10_polymorphisme",
        "poly6.cpp",
        "L'effacement de type et son prix",
        "std::function accepte n'importe quel appelable, et le paie : une\nindirection, et une allocation des que la capture depasse son tampon.\nLe compteur de copies le montre.",
        "Quand le type est connu a la compilation, un parametre template suffit\net ne coute rien. Garde std::function pour ce qu'on doit stocker.",
        "c++20",
    },
    {
        "vec1",
        "11_conteneur",
        "vec1.cpp",
        "Le stockage brut",
        "Reserver de la place n'est pas construire des objets. Ici la reservation\nconstruit dix Sonde dont personne n'a rien demande.",
        "::operator new donne de la memoire nue. Un placement new y construit un\nobjet, au moment de l'ajout et pas avant.",
        "c++20",
    },
    {
        "vec2",
        "11_conteneur",
        "vec2.cpp",
        "La croissance",
        "Quand le tampon est plein : en prendre un plus grand, y deplacer les\nelements, DETRUIRE les anciens, LIBERER l'ancien bloc. Une etape manque,\net les compteurs ne s'equilibrent plus.",
        "Un objet construit par placement new doit etre detruit par un appel\nexplicite au destructeur. Aucun delete ne le fera pour toi.",
        "c++20",
    },
    {
        "vec3",
        "11_conteneur",
        "vec3.cpp",
        "emplace_back et le transfert parfait",
        "emplace_back construit un temporaire puis le deplace : une construction\nde trop. Il devrait construire directement a sa place.",
        "template <typename... Args>, et un placement new qui passe\nstd::forward<Args>(args)... au constructeur.",
        "c++20",
    },
    {
        "vec4",
        "11_conteneur",
        "vec4.cpp",
        "move_if_noexcept, ecrit a la main",
        "La croissance deplace inconditionnellement. Pour un type dont le\ndeplacement peut lever, ca fait perdre la garantie forte.",
        "std::move_if_noexcept rend une rvalue quand le deplacement est noexcept,\net une lvalue sinon : la copie reprend la main toute seule.",
        "c++20",
    },
    {
        "vec5",
        "11_conteneur",
        "vec5.cpp",
        "La garantie forte",
        "Si une copie leve au milieu de la croissance, le vecteur doit etre\nexactement comme avant. Ici l'ancien tampon est deja parti.",
        "Remplis entierement le nouveau tampon d'abord. Tant qu'il n'est pas\ncomplet, l'ancien reste le seul valide : on ne le touche pas.",
        "c++20",
    },
    {
        "vec6",
        "11_conteneur",
        "vec6.cpp",
        "size, capacity, et l'invalidation",
        "La capacite est de la place reservee, la taille le nombre d'objets\nvraiment construits. Confondre les deux fait lire du stockage brut.",
        "Parcours jusqu'a taille. La capacite ne sert qu'a decider quand grandir.",
        "c++20",
    },
    {
        "al1",
        "12_alloc",
        "al1.cpp",
        "Compter les allocations",
        "Surcharge ::operator new et regarde. Cette fonction alloue plusieurs fois\nsans que rien dans son code ne le montre.",
        "Un parametre std::string par valeur alloue une fois par appel des que la\nchaine depasse la petite optimisation. std::string_view ne possede rien.",
        "c++20",
    },
    {
        "al2",
        "12_alloc",
        "al2.cpp",
        "Une arene sur la pile",
        "Un tampon local, une ressource monotone posee dessus, et le conteneur\nn'appelle plus jamais le tas. Le compteur doit rester a zero.",
        "std::pmr::monotonic_buffer_resource sur un tableau local, et\nstd::pmr::vector qui recoit son adresse a la construction.",
        "c++20",
    },
    {
        "al3",
        "12_alloc",
        "al3.cpp",
        "La propagation de l'allocateur",
        "Le vecteur utilise bien l'arene ; ses chaines, elles, allouent toujours\nsur le tas. Un std::string ne sait pas d'ou vient son conteneur.",
        "std::pmr::string, dont l'allocateur est propage par le conteneur.\nC'est le piege numero un de pmr.",
        "c++20",
    },
    {
        "al4",
        "12_alloc",
        "al4.cpp",
        "Le small vector",
        "Le tampon interne est declare et jamais utilise : tout part sur le tas\ndes le premier ajout.",
        "Sers depuis le tampon interne tant que la taille tient dedans, et\nbascule sur le tas au franchissement, en deplacant ce qui est deja la.",
        "c++20",
    },
    {
        "al5",
        "12_alloc",
        "al5.cpp",
        "Le pool",
        "Beaucoup de petites allocations de meme taille, une par element. Une\nressource en pool prend de gros morceaux et les decoupe elle-meme.",
        "std::pmr::unsynchronized_pool_resource. Le compteur global mesure les\nallocations EN AMONT, pas celles que le pool sert depuis ses morceaux.",
        "c++20",
    },
    {
        "al6",
        "12_alloc",
        "al6.cpp",
        "Ecrire sa ressource memoire",
        "do_allocate recoit une taille ET un alignement. Ignorer le second rend\ndes adresses que le type n'accepte pas, et UBSan arrete tout.",
        "Arrondis la position courante au multiple superieur de l'alignement\ndemande avant de servir. C'est exactement l'exercice alloc2, en C++.",
        "c++20",
    },
    {
        "thr1",
        "13_threads",
        "thr1.cpp",
        "La course de donnees",
        "Deux fils incrementent le meme compteur, et il en manque la moitie.\nAucun outil ne te le dira ici : c'est le chiffre qui parle.",
        "std::atomic<long> rend l'increment indivisible. Verifie aussi\nis_always_lock_free : un atomique trop gros prend un verrou en douce.",
        "c++20",
    },
    {
        "thr2",
        "13_threads",
        "thr2.cpp",
        "La section critique",
        "Un std::vector n'est pas protege : deux fils qui font push_back en meme\ntemps le corrompent, et AddressSanitizer finit par s'en apercevoir.",
        "std::lock_guard prend le verrou a la construction et le rend a la\ndestruction, exception comprise. On n'ecrit jamais lock et unlock a la\nmain.",
        "c++20",
    },
    {
        "thr3",
        "13_threads",
        "thr3.cpp",
        "Un thread qu'on n'attend pas",
        "Un std::thread encore joignable au moment de sa destruction appelle\nstd::terminate. Pas d'avertissement, pas d'exception : le programme\nmeurt.",
        "std::jthread joint dans son destructeur, et accepte un stop_token pour\ndemander l'arret. C'est le defaut a prendre depuis C++20.",
        "c++20",
    },
    {
        "thr4",
        "13_threads",
        "thr4.cpp",
        "Atomique n'est pas section critique",
        "Chaque operation est atomique, et pourtant le stock devient negatif :\ndeux fils passent le test avant que l'un ne decremente.",
        "Ce n'est pas la lecture ni l'ecriture qu'il faut rendre atomique, c'est\nla SEQUENCE. compare_exchange_weak en boucle, ou un mutex.",
        "c++20",
    },
    {
        "thr5",
        "13_threads",
        "thr5.cpp",
        "L'exception qui traverse un fil",
        "Une exception qui sort de la fonction d'un std::thread ne remonte nulle\npart : elle appelle std::terminate.",
        "std::async range l'exception dans le future, et future::get la relance\ndans le fil appelant, ou tu peux enfin l'attraper.",
        "c++20",
    },
    {
        "thr6",
        "13_threads",
        "thr6.cpp",
        "La contention se mesure",
        "Le resultat est juste, mais chaque tour de boucle touche le compteur\npartage. Un second compteur montre le nombre reel d'acces.",
        "Accumule dans une variable locale, et ne touche au compteur partage\nqu'une seule fois, a la fin. Meme resultat, mille fois moins d'acces.",
        "c++20",
    },
    {
        "coro1",
        "14_coroutines",
        "coro1.cpp",
        "Le contrat du promise_type",
        "Une fonction devient coroutine des qu'elle contient co_yield, co_await\nou co_return. Le compilateur reclame alors un promise_type complet, et\nil manque un membre.",
        "Le contrat : get_return_object, initial_suspend, final_suspend qui doit\netre noexcept, return_void ou return_value, unhandled_exception. Lis le\nmessage du compilateur, il nomme celui qui manque.",
        "c++20",
    },
    {
        "coro2",
        "14_coroutines",
        "coro2.cpp",
        "co_yield et le generateur",
        "Le generateur saute une valeur. Le coupable est le couple\ninitial_suspend et la premiere reprise : quelque chose s'execute trop\ntot.",
        "Avec suspend_always en initial_suspend, rien ne tourne avant la\npremiere demande. L'iterateur reprend PUIS lit, jamais l'inverse.",
        "c++20",
    },
    {
        "coro3",
        "14_coroutines",
        "coro3.cpp",
        "Le cadre ne se detruit pas tout seul",
        "Le cadre d'une coroutine est alloue sur le tas, et rien ne le libere a\nta place. LeakSanitizer n'existe pas ici : c'est le compteur de la Sonde\nqui montre la fuite.",
        "destroy() dans le destructeur du generateur. Et la regle de cinq :\nnon copiable, deplacable, sinon deux poignees detruiraient le meme cadre.",
        "c++20",
    },
    {
        "coro4",
        "14_coroutines",
        "coro4.cpp",
        "Le parametre pris par reference",
        "LE bug des coroutines. Les parametres sont copies dans le cadre, mais\nune reference ne copie que la reference : le temporaire de l'appelant\nmeurt a la premiere suspension.",
        "Prends le parametre PAR VALEUR. Il est alors copie dans le cadre, qui\nlui survit. Rien ne t'avertira jamais de cette faute.",
        "c++20",
    },
    {
        "coro5",
        "14_coroutines",
        "coro5.cpp",
        "Ecrire un awaitable",
        "co_await appelle trois membres dans un ordre precis. L'un manque, a la\nmauvaise signature, ou rend la mauvaise reponse.",
        "await_ready dit si la valeur est deja la, await_suspend recoit la\npoignee et decide de suspendre, await_resume rend le resultat a la\nreprise.",
        "c++20",
    },
    {
        "coro6",
        "14_coroutines",
        "coro6.cpp",
        "Ce que ca alloue",
        "Un cadre de coroutine part sur le tas. En creer un par tour de boucle\nse voit tout de suite quand on compte les appels a operator new.",
        "Un seul generateur, repris autant de fois qu'il faut, au lieu d'un\ngenerateur par valeur produite.",
        "c++20",
    },
};

const std::vector<Question> BANQUE = {
    {
        "00_intro",
        "Devant un mur d'erreurs de template, par ou commencer ?",
        {
            "Par la derniere ligne",
            "Par la premiere ligne contenant 'error:'",
            "Par la ligne la plus longue",
            "En recompilant avec -w",
        },
        1,
        "La premiere 'error:' est la cause ; tout ce qui suit en decoule.\nCherche ensuite 'requested here' ou 'in instantiation of' : c'est la\nligne de TON code qui a declenche l'instanciation. GCC, lui, ecrit\n'required from here' au meme endroit.",
    },
    {
        "01_bases",
        "Que fait 'for (auto x : conteneur)' ?",
        {
            "Une reference sur chaque element",
            "Une copie de chaque element",
            "Un pointeur sur chaque element",
            "Cela depend du conteneur",
        },
        1,
        "'auto' deduit le type sans reference ni const : chaque tour COPIE.\nSur un vector<string> de mille elements, c'est mille allocations.\nEcris 'const auto &' par defaut.",
    },
    {
        "01_bases",
        "Que contient 'std::vector<int> v{3, 5}' ?",
        {
            "Trois cases valant 5",
            "Deux cases valant 3 et 5",
            "Cinq cases valant 3",
            "Une case valant 35",
        },
        1,
        "Les accolades preferent TOUJOURS le constructeur a liste d'initialisation\nquand il existe. Pour trois cases valant 5, il faut des parentheses :\nstd::vector<int> v(3, 5).",
    },
    {
        "02_valeurs",
        "Que fait std::move au moment de l'execution ?",
        {
            "Il copie l'objet",
            "Il deplace l'objet",
            "Rien du tout",
            "Il libere l'objet source",
        },
        2,
        "std::move est un simple cast vers une reference rvalue. Il ne bouge pas\nun octet : il change la SURCHARGE choisie, et c'est le constructeur de\ndeplacement qui fait le travail — s'il existe.",
    },
    {
        "02_valeurs",
        "Pourquoi 'return std::move(local);' est-il une erreur ?",
        {
            "C'est plus lent a compiler",
            "Cela empeche l'elision de copie",
            "Cela provoque une fuite",
            "Ce n'est pas une erreur",
        },
        1,
        "Depuis C++17, un objet local renvoye est construit DIRECTEMENT chez\nl'appelant : zero copie, zero deplacement. Ajouter std::move transforme\nl'expression en rvalue et force un deplacement inutile.",
    },
    {
        "03_raii",
        "Quand le destructeur d'un objet local est-il appele ?",
        {
            "A la fin du programme",
            "Quand on appelle delete",
            "A la fermeture de l'accolade, quoi qu'il arrive",
            "Jamais si on sort par un return",
        },
        2,
        "C'est toute la garantie de RAII : return anticipe, exception, break —\nle destructeur passe. C'est pour cela qu'un unique_ptr ne fuit jamais\nla ou un delete manuel fuit.",
    },
    {
        "03_raii",
        "Que coute une copie de shared_ptr par rapport a unique_ptr ?",
        {
            "Rien",
            "Une incrementation atomique du compteur",
            "Une allocation",
            "Une copie de l'objet pointe",
        },
        1,
        "Le compteur de shared_ptr est atomique, pour rester correct entre threads.\nUne incrementation atomique coute bien plus qu'une incrementation normale.\nPasse un shared_ptr par reference constante quand tu ne stockes pas.",
    },
    {
        "04_regle_zero",
        "Que se passe-t-il quand on declare un destructeur ?",
        {
            "Rien de particulier",
            "Le compilateur cesse de generer les operations de deplacement",
            "La copie devient interdite",
            "La classe devient abstraite",
        },
        1,
        "Declarer un destructeur (meme vide, meme '= default') supprime la\ngeneration implicite du constructeur et de l'affectation de deplacement.\nTout retombe silencieusement sur la copie, et les performances avec.",
    },
    {
        "04_regle_zero",
        "La regle de zero, c'est :",
        {
            "Ne jamais ecrire de constructeur",
            "Laisser les membres gerer leurs ressources",
            "Tout mettre en private",
            "Utiliser zero allocation",
        },
        1,
        "Si chaque membre sait deja se copier, se deplacer et se detruire —\nstring, vector, unique_ptr — la classe n'a besoin d'AUCUNE des cinq\noperations. C'est la meilleure classe : celle qu'on n'ecrit pas.",
    },
    {
        "05_conteneurs",
        "Que devient un pointeur vers un element apres push_back ?",
        {
            "Il reste valide",
            "Il peut etre invalide si le vecteur a realloue",
            "Il pointe sur le nouvel element",
            "Il devient nullptr",
        },
        1,
        "Un vector garde ses elements dans un bloc continu. S'il n'y a plus de\ncapacite, il en alloue un nouveau, deplace tout, et libere l'ancien.\nTout pointeur, reference ou iterateur vers l'ancien bloc devient pendant.",
    },
    {
        "05_conteneurs",
        "Quelle est la difference entre push_back et emplace_back ?",
        {
            "Aucune",
            "emplace_back construit l'objet directement dans le conteneur",
            "push_back est plus rapide",
            "emplace_back ne fonctionne que sur les types simples",
        },
        1,
        "push_back recoit un objet deja construit et le copie ou le deplace.\nemplace_back recoit les ARGUMENTS du constructeur et construit sur place :\nune construction, zero copie, zero deplacement.",
    },
    {
        "05_conteneurs",
        "Quand preferer std::map a std::unordered_map ?",
        {
            "Quand on veut la recherche la plus rapide",
            "Quand on veut parcourir dans l'ordre des cles",
            "Quand les cles sont des chaines",
            "map est toujours preferable",
        },
        1,
        "unordered_map cherche en temps constant moyen, map en log(n). Mais map\nest un arbre trie : elle garantit un parcours ordonne, des bornes\n(lower_bound), et la stabilite des iterateurs a l'insertion.",
    },
    {
        "06_algos",
        "Que renvoie std::find_if quand rien ne correspond ?",
        {
            "nullptr",
            "L'iterateur end()",
            "Le premier element",
            "Il leve une exception",
        },
        1,
        "Toujours comparer a end() AVANT de dereferencer. Comparer a nullptr ne\ncompile meme pas sur la plupart des conteneurs : un iterateur n'est pas\nun pointeur.",
    },
    {
        "06_algos",
        "Une vue de std::ranges, ca coute :",
        {
            "Une copie du conteneur",
            "Une allocation",
            "Rien : elle est paresseuse et ne possede rien",
            "Un parcours complet a la creation",
        },
        2,
        "Une vue est un objet minuscule qui garde des iterateurs et un predicat.\nRien n'est calcule tant qu'on ne la parcourt pas, et le conteneur d'origine\nn'est ni copie ni modifie. Attention en revanche a ce qu'il lui survive.",
    },
    {
        "07_templates",
        "Pourquoi la definition d'un template va-t-elle dans l'en-tete ?",
        {
            "Par convention, un .cpp marcherait aussi",
            "Parce que le compilateur doit la voir la ou le type est connu",
            "Parce que c'est plus rapide a compiler",
            "Parce que l'editeur de liens refuse les templates",
        },
        1,
        "Un template n'est pas du code : aucune fonction n'existe tant qu'un type ne\nl'instancie pas. Chaque unite de compilation qui l'utilise doit donc voir la\ndefinition complete. L'alternative est l'instanciation explicite dans un .cpp,\nquand la liste des types est connue d'avance.",
    },
    {
        "07_templates",
        "Quelle est la difference entre if et if constexpr ?",
        {
            "Aucune, c'est du sucre syntaxique",
            "if constexpr ne compile pas la branche non prise",
            "if constexpr est plus rapide a l'execution",
            "if constexpr n'accepte que des bool",
        },
        1,
        "Un if ordinaire exige que ses deux branches compilent, meme quand la\ncondition est connue a la compilation. if constexpr ecarte la branche non\nprise avant l'analyse : c'est ce qui permet d'ecrire valeur.size() dans une\nbranche qu'un int ne prendra jamais.",
    },
    {
        "07_templates",
        "Dans un template a parametre deduit, que designe T&& ?",
        {
            "Une reference sur rvalue, toujours",
            "Une reference universelle : lvalue ou rvalue selon l'argument",
            "Une reference sur reference",
            "Un pointeur de pointeur",
        },
        1,
        "Quand T est deduit, les references se replient : passe une lvalue et T\ndevient T&, donc T&& devient T& (& && donne &). C'est pourquoi on transmet\navec std::forward<T> et non std::move, qui ferait une rvalue meme de ce qui\nn'en est pas une.",
    },
    {
        "08_erreurs",
        "Que coute une exception qui n'est jamais levee ?",
        {
            "Un test a chaque appel de fonction",
            "Rien a l'execution : des tables rangees a part dans le binaire",
            "Une allocation par bloc try",
            "Un compteur atomique par objet",
        },
        1,
        "C'est le modele dit zero-cost : le chemin normal ne contient aucune\ninstruction supplementaire, le deroulement est decrit par des tables placees\ndans une section separee. Le prix se paie entierement quand l'exception part,\net il est eleve : de l'ordre de la microseconde.",
    },
    {
        "08_erreurs",
        "Pourquoi marquer noexcept un constructeur de deplacement ?",
        {
            "Pour accelerer la compilation",
            "Sinon vector copie au lieu de deplacer quand il realloue",
            "C'est purement documentaire",
            "Pour que le destructeur soit appele",
        },
        1,
        "vector utilise std::move_if_noexcept : pour tenir sa garantie forte, il ne\ndeplace que si le deplacement ne peut pas lever. Sans noexcept, et si le type\nest copiable, chaque reallocation copie tous les elements. C'est le piege le\nplus cher du C++ moderne, et il est invisible a la lecture.",
    },
    {
        "08_erreurs",
        "Pourquoi attraper par 'const std::exception &' plutot que par valeur ?",
        {
            "C'est seulement plus rapide",
            "Par valeur, l'objet est decoupe et perd son type derive",
            "Par valeur, cela ne compile pas",
            "Il n'y a aucune difference",
        },
        1,
        "Attraper par valeur construit un objet du type ecrit dans le catch : la\npartie derivee est perdue, et what() ne renvoie plus que \"std::exception\".\nLa reference designe l'objet reellement leve, avec sa vraie fonction\nvirtuelle. Et les catch se rangent du plus derive au plus general.",
    },
    {
        "09_layout",
        "Pourquoi un parcours de std::list est-il plus lent qu'un parcours de std::vector ?",
        {
            "Parce que list alloue un noeud par element",
            "Parce que ses noeuds sont disperses, ce que le prefetcher ne sait pas deviner",
            "Parce que list n'a pas d'iterateur a acces direct",
            "Parce que list range deux pointeurs par element",
        },
        1,
        "Les trois autres reponses sont vraies aussi, mais celle qui domine a\nl'execution est la disposition. Le vector est contigu : le materiel devine la\nsuite et charge d'avance. Une liste saute d'une adresse a l'autre, chaque saut\nest un defaut de cache, et aucune prediction n'est possible.",
    },
    {
        "09_layout",
        "Que fait [[no_unique_address]] ?",
        {
            "Il supprime le membre",
            "Il autorise un membre vide a ne pas occuper d'octet propre",
            "Il aligne le membre sur une ligne de cache",
            "Il rend le membre commun a toutes les instances",
        },
        1,
        "La regle veut que deux membres distincts aient deux adresses distinctes, ce\nqui coute un octet plus le remplissage meme pour une classe sans etat.\n[[no_unique_address]], depuis C++20, leve cette obligation : le membre vide\npeut partager l'adresse du suivant, et la classe retombe a ses vraies donnees.",
    },
    {
        "09_layout",
        "Le faux partage, c'est :",
        {
            "Deux fils qui lisent la meme variable",
            "Deux fils qui ecrivent deux variables voisines de la meme ligne de cache",
            "Un shared_ptr copie trop souvent",
            "Une donnee protegee par le mauvais mutex",
        },
        1,
        "La coherence de cache travaille par LIGNE, pas par variable. Deux compteurs\nseparees de quelques octets s'invalident mutuellement a chaque ecriture, meme\nsi aucun fil ne touche la donnee de l'autre. Le remede est de les ecarter\nd'une ligne entiere avec alignas.",
    },
    {
        "10_polymorphisme",
        "Que se passe-t-il quand on ecrit 'delete base' sans destructeur virtuel ?",
        {
            "Le bon destructeur est retrouve grace au RTTI",
            "Comportement indefini : en pratique le destructeur de la derivee n'est pas appele",
            "Le compilateur refuse de compiler",
            "shared_ptr regle le probleme dans tous les cas",
        },
        1,
        "L'appel est resolu sur le type ECRIT : seule la partie base est detruite, et\ntout ce que la derivee possedait fuit. C'est un comportement indefini, donc\nrien n'est garanti. Curiosite utile : shared_ptr, lui, capture le destructeur\ndu type reel a la construction ; unique_ptr non.",
    },
    {
        "10_polymorphisme",
        "A quoi sert 'override' ?",
        {
            "A rendre la fonction virtuelle",
            "A faire echouer la compilation quand la signature ne redefinit rien",
            "A empecher les derivees d'aller plus loin",
            "A accelerer l'appel virtuel",
        },
        1,
        "override ne change pas une ligne du code genere : il fait verifier par le\ncompilateur qu'une fonction de base correspond bien. Sans lui, un const de\ntrop cree une SURCHARGE muette, la fonction de base continue d'etre appelee, et\nrien ne le signale. 'final' interdit d'aller plus loin et permet parfois de\ndevirtualiser l'appel.",
    },
    {
        "10_polymorphisme",
        "Le CRTP fait disparaitre :",
        {
            "Le code duplique",
            "Le pointeur de table virtuelle et l'appel indirect",
            "Le besoin d'ecrire des templates",
            "Le temps de compilation",
        },
        1,
        "Le choix se fait a la compilation : plus de table, plus de pointeur dans\nl'objet, et l'appel redevient inlinable. En echange on perd le choix a\nl'execution et le conteneur heterogene, chaque derivee ayant sa propre base,\net le temps de compilation, lui, augmente.",
    },
    {
        "11_conteneur",
        "Comment reserve-t-on de la place sans construire d'objets ?",
        {
            "new T[capacite]",
            "::operator new(capacite * sizeof(T)), puis un placement new par element ajoute",
            "std::vector<T>(capacite)",
            "malloc, puis une affectation",
        },
        1,
        "new T[capacite] construit capacite objets par defaut, ce qui exige un\nconstructeur par defaut et coute autant de constructions inutiles.\n::operator new ne rend que des octets ; c'est le placement new qui construit,\nau moment de l'ajout, et l'appel explicite du destructeur qui detruit.",
    },
    {
        "11_conteneur",
        "Pourquoi la capacite d'un vecteur double-t-elle au lieu d'augmenter d'un cran ?",
        {
            "Pour eviter la fragmentation",
            "Pour que le cout moyen d'un ajout reste constant",
            "Parce que l'allocateur l'exige",
            "Pour aligner le bloc",
        },
        1,
        "Avec une croissance multiplicative, chaque element est deplace en moyenne une\nfois sur la duree de vie du vecteur : n ajouts coutent un temps proportionnel a\nn. Une croissance d'un cran a chaque fois donnerait un cout total en n au\ncarre. Le facteur exact importe peu : 1.5 reutilise mieux la memoire liberee,\n2 est plus simple.",
    },
    {
        "11_conteneur",
        "Quelle sequence donne la garantie forte pendant la croissance ?",
        {
            "Liberer l'ancien tampon, puis remplir le nouveau",
            "Remplir entierement le nouveau tampon, puis seulement detruire et liberer l'ancien",
            "Copier element par element en liberant au fur et a mesure",
            "Attraper l'exception et recommencer",
        },
        1,
        "Tant que le nouveau tampon n'est pas complet, l'ancien est le seul etat\nvalide : on n'y touche pas. Si une construction leve, on detruit ce qu'on a\ndeja mis dans le nouveau, on le libere, et on relance l'exception — le vecteur\nn'a pas bouge. C'est aussi la raison d'etre de std::move_if_noexcept.",
    },
    {
        "12_alloc",
        "Que fait std::pmr::monotonic_buffer_resource ?",
        {
            "Elle libere chaque bloc individuellement",
            "Elle sert depuis un tampon donne et ne libere rien avant sa propre destruction",
            "Elle compte les allocations",
            "Elle synchronise les allocations entre threads",
        },
        1,
        "C'est l'arene du cours de C, en C++ : un curseur qui avance dans un tampon\nfourni, do_deallocate qui ne fait rien, et tout rendu d'un coup a la fin. Posee\nsur un tableau local, elle fait tomber a zero le nombre d'appels au tas pour\ntoute la duree d'un calcul.",
    },
    {
        "12_alloc",
        "Pourquoi un std::pmr::vector<std::string> alloue-t-il encore sur le tas ?",
        {
            "Parce que pmr ne marche pas avec les chaines",
            "Parce que std::string a son propre allocateur et ignore la ressource du conteneur",
            "Parce que le vecteur copie ses elements",
            "Parce que la ressource est saturee",
        },
        1,
        "L'allocateur d'un conteneur pmr se propage a ses elements — mais seulement\naux elements qui savent en recevoir un. std::string n'est pas un type pmr : il\ngarde std::allocator et va au tas. Il faut std::pmr::string. C'est le piege\nnumero un de pmr, et il ne produit aucun avertissement.",
    },
    {
        "12_alloc",
        "Que recoit do_allocate dans une memory_resource, en plus de la taille ?",
        {
            "Rien d'autre",
            "L'alignement demande, qu'il est obligatoire de respecter",
            "Le type de l'objet",
            "Le nombre d'elements",
        },
        1,
        "La signature est do_allocate(std::size_t octets, std::size_t alignement).\nIgnorer le second parametre rend des adresses que le type n'accepte pas : c'est\nun comportement indefini, qu'UBSan attrape sur le premier acces. Arrondir la\nposition courante au multiple superieur suffit.",
    },
    {
        "13_threads",
        "Qu'est-ce qu'une course de donnees, exactement ?",
        {
            "Deux threads qui lisent la meme variable",
            "Deux acces au meme emplacement, dont au moins un en ecriture, sans relation happens-before",
            "Deux threads qui prennent le meme mutex",
            "Un resultat qui change d'une execution a l'autre",
        },
        1,
        "La definition compte, parce que la consequence est un comportement INDEFINI et\npas un simple resultat imprevisible : le compilateur a le droit d'optimiser en\nsupposant qu'il n'y en a pas. Deux lectures ne font pas une course, et deux\nacces separes par un verrou ou par une paire acquire/release non plus.",
    },
    {
        "13_threads",
        "Pourquoi 'if (stock > 0) stock--;' reste-t-il faux avec un std::atomic<int> ?",
        {
            "Parce qu'il faut memory_order_seq_cst",
            "Parce que chaque operation est atomique, mais pas la sequence des deux",
            "Parce qu'un atomique ne peut pas etre decremente",
            "Parce que l'operateur -- n'est pas atomique",
        },
        1,
        "Entre le test et la modification, un autre fil peut passer. Les deux operations\nsont indivisibles chacune, leur enchainement ne l'est pas. Il faut une seule\noperation qui teste et modifie ensemble — compare_exchange_weak en boucle — ou\nun mutex. C'est la faute la plus repandue avec les atomiques.",
    },
    {
        "13_threads",
        "Que se passe-t-il si un std::thread encore joignable est detruit ?",
        {
            "Il est detache automatiquement",
            "std::terminate est appele",
            "Le destructeur attend la fin du thread",
            "Une exception est levee",
        },
        1,
        "Le comite a refuse de choisir entre join implicite, qui bloquerait sans qu'on\nle voie, et detach implicite, qui laisserait un thread lire de la memoire\nmorte : il a donc rendu l'oubli mortel. std::jthread, depuis C++20, tranche en\nfaveur du join dans le destructeur, et c'est le defaut a prendre.",
    },
    {
        "14_coroutines",
        "Qu'est-ce qui transforme une fonction en coroutine ?",
        {
            "Un mot-cle dans sa signature",
            "La presence de co_await, co_yield ou co_return dans son corps",
            "Le type de retour",
            "L'attribut [[coroutine]]",
        },
        1,
        "Rien dans la signature ne le montre, ce qui en fait un piege de relecture : le\ncorps seul decide. Le type de retour, lui, doit fournir un promise_type, mais\nc'est une consequence, pas la cause. Ajouter un co_return dans une fonction\nordinaire change donc entierement sa nature.",
    },
    {
        "14_coroutines",
        "Pourquoi ne faut-il jamais prendre un parametre de coroutine par reference ?",
        {
            "Parce que c'est plus lent",
            "Parce que seule la reference est copiee dans le cadre : la valeur visee peut mourir a la premiere suspension",
            "Parce que le compilateur le refuse",
            "Parce que les references ne survivent pas a co_await",
        },
        1,
        "Les parametres sont copies dans le cadre de la coroutine — mais copier une\nreference ne copie pas ce qu'elle designe. Un temporaire passe par const & est\ndetruit a la fin de l'expression d'appel, donc avant la premiere reprise, et\nla coroutine lit de la memoire morte. Prendre par valeur regle tout, et rien\nne t'avertira jamais.",
    },
    {
        "14_coroutines",
        "Ou vit l'etat d'une coroutine suspendue ?",
        {
            "Sur la pile de l'appelant",
            "Dans un cadre alloue sur le tas, sauf elision",
            "Dans des registres",
            "Dans le promise_type, qui est statique",
        },
        1,
        "Une coroutine survit au retour de la fonction qui l'a appelee : ses locales ne\npeuvent donc pas rester sur la pile. Le compilateur alloue un cadre, par\noperator new du promise_type s'il en fournit un. L'elision est permise quand la\nduree de vie du cadre est visiblement contenue dans celle de l'appelant, mais\nelle n'est jamais garantie par la norme.",
    },
};

}

const std::vector<Exercice> &catalogue() { return EXERCICES; }

const std::vector<Question> &questions() { return BANQUE; }
