#include "catalogue.hpp"

namespace {

const std::vector<Exercice> EXERCICES = {
    {
        "intro1",
        "00_intro",
        "intro1.cpp",
        "Comment ca marche",
        "Rien a corriger : ce fichier tourne deja.\nOuvre-le, passe PAS_FINI a false, sauvegarde.",
        "La ligne est 'const bool PAS_FINI = true;'. Remplace true par false.",
        "c++20",
    },
    {
        "intro2",
        "00_intro",
        "intro2.cpp",
        "Lire une erreur du compilateur",
        "Ce fichier ne compile pas. Lis le message ci-dessus : fichier, ligne,\ncolonne, cause. Corrige, puis passe PAS_FINI a false.",
        "En C++, chaque instruction se termine par un point-virgule.",
        "c++20",
    },
    {
        "intro3",
        "00_intro",
        "intro3.cpp",
        "Lire une erreur de template",
        "Le compilateur va cracher trente lignes. Ne les lis pas dans l'ordre :\ncherche 'error:' tout en haut, puis 'required from here' pour trouver\nTA ligne. Le comparateur ne prend pas le bon type.",
        "std::sort sur un vector<string> passe des string au comparateur,\npas des int.",
        "c++20",
    },
    {
        "base1",
        "01_bases",
        "base1.cpp",
        "auto copie par defaut",
        "'auto x : conteneur' fait une COPIE a chaque tour. La Sonde compte les\ncopies : fais tomber le compteur a zero.",
        "Boucle par reference constante : 'for (const auto &sonde : sondes)'.",
        "c++20",
    },
    {
        "base2",
        "01_bases",
        "base2.cpp",
        "Les references",
        "Une reference est un autre nom pour la meme variable : pas de copie,\npas de pointeur, et elle ne peut jamais etre nulle ni changer de cible.",
        "'int &lien = valeur;' fait de lien un alias. Ecrire dans lien ecrit\ndans valeur.",
        "c++20",
    },
    {
        "base3",
        "01_bases",
        "base3.cpp",
        "const et constexpr",
        "'const' promet de ne pas modifier. 'constexpr' calcule a la compilation.\nRends la fonction utilisable dans un static_assert.",
        "Marque la fonction constexpr. Une fonction constexpr peut aussi etre\nappelee normalement a l'execution.",
        "c++20",
    },
    {
        "base4",
        "01_bases",
        "base4.cpp",
        "Le piege des accolades",
        "std::vector<int> v(3, 5) fait trois cases valant 5.\nstd::vector<int> v{3, 5} fait DEUX cases valant 3 et 5.\nLes accolades preferent toujours la liste d'initialisation.",
        "Utilise des parentheses pour appeler le constructeur (nombre, valeur).",
        "c++20",
    },
    {
        "base5",
        "01_bases",
        "base5.cpp",
        "Liaison structurée",
        "Une liaison structuree decompose un agregat en variables nommees.\nUtilise-la pour parcourir la map sans passer par .first et .second.",
        "for (const auto &[cle, valeur] : scores) { ... }",
        "c++20",
    },
    {
        "base6",
        "01_bases",
        "base6.cpp",
        "nullptr, pas NULL",
        "NULL est un entier deguise : il peut choisir la mauvaise surcharge.\nnullptr a son propre type et ne se trompe jamais.",
        "Passe nullptr au lieu de 0 ou NULL.",
        "c++20",
    },
    {
        "val1",
        "02_valeurs",
        "val1.cpp",
        "Passer par valeur copie",
        "Ce parametre est pris par valeur : chaque appel copie l'objet entier.\nLa Sonde le compte. Fais tomber le compteur a zero.",
        "Prends le parametre par reference constante : const verif::Sonde &",
        "c++20",
    },
    {
        "val2",
        "02_valeurs",
        "val2.cpp",
        "Le retour par valeur est gratuit",
        "Renvoyer un objet local ne le copie pas : le compilateur le construit\ndirectement chez l'appelant. C'est l'elision de copie, obligatoire\ndepuis C++17. Ne l'empeche pas avec un std::move inutile.",
        "Un 'return std::move(local)' EMPECHE l'elision et force un deplacement.\nEcris simplement 'return local;'.",
        "c++20",
    },
    {
        "val3",
        "02_valeurs",
        "val3.cpp",
        "std::move ne deplace rien",
        "std::move ne fait AUCUN travail : c'est une conversion de type qui dit\n'tu peux me piller'. C'est le constructeur de deplacement qui agit.\nUtilise-le pour eviter la copie dans le vecteur.",
        "std::move(sonde) transforme la lvalue en rvalue, ce qui selectionne\nla surcharge de deplacement de push_back.",
        "c++20",
    },
    {
        "val4",
        "02_valeurs",
        "val4.cpp",
        "Le parametre puits",
        "Quand une fonction STOCKE son argument, le prendre par valeur puis le\ndeplacer est la bonne recette : un seul deplacement depuis une rvalue.",
        "Prends le parametre par valeur, puis 'stock.push_back(std::move(sonde));'",
        "c++20",
    },
    {
        "val5",
        "02_valeurs",
        "val5.cpp",
        "Une reference qui survit a sa cible",
        "Cette fonction renvoie une reference vers une variable locale : elle ne\ndesigne plus rien au retour. AddressSanitizer le voit.\nRenvoie par valeur.",
        "Change le type de retour en 'std::string' au lieu de 'const std::string &'.",
        "c++20",
    },
    {
        "raii1",
        "03_raii",
        "raii1.cpp",
        "Le destructeur, a la sortie de portee",
        "Un objet local est detruit a la fermeture de l'accolade, quoi qu'il arrive.\nC'est toute la mecanique de RAII. Ouvre une portee pour que ce soit vrai.",
        "Entoure la creation de la sonde par une paire d'accolades : { ... }",
        "c++20",
    },
    {
        "raii2",
        "03_raii",
        "raii2.cpp",
        "new sans delete sur le chemin d'erreur",
        "Ce code libere bien... sauf quand il sort tot. La Sonde compte les\nconstructions et les destructions : elles doivent s'equilibrer.\nUtilise un unique_ptr et le probleme disparait.",
        "std::make_unique<verif::Sonde>(valeur) libere tout seul, y compris sur\nun return anticipe.",
        "c++20",
    },
    {
        "raii3",
        "03_raii",
        "raii3.cpp",
        "unique_ptr ne se copie pas",
        "unique_ptr represente une propriete EXCLUSIVE : il ne se copie pas,\nil se deplace. C'est verifie a la compilation.",
        "std::move(premier) transfere la propriete. Apres, premier vaut nullptr.",
        "c++20",
    },
    {
        "raii4",
        "03_raii",
        "raii4.cpp",
        "shared_ptr et son compteur",
        "shared_ptr partage la propriete : il compte les proprietaires, et libere\nquand le compteur tombe a zero. Ce compteur est ATOMIQUE, donc chaque\ncopie coute une operation synchronisee.",
        "use_count() donne le nombre de proprietaires. Une copie l'incremente,\nune sortie de portee le decremente.",
        "c++20",
    },
    {
        "raii5",
        "03_raii",
        "raii5.cpp",
        "Ecrire son garde de portee",
        "RAII n'est pas reserve a la memoire : tout ce qui s'ouvre et se ferme\nen profite. Ecris un garde qui execute une action a la destruction.",
        "Stocke l'action dans un membre, et appelle-la dans le destructeur.",
        "c++20",
    },
    {
        "raii6",
        "03_raii",
        "raii6.cpp",
        "L'ordre de destruction",
        "Les objets sont detruits dans l'ordre INVERSE de leur construction.\nComplete la trace attendue.",
        "Construits a, b, c : detruits c, b, a.",
        "c++20",
    },
    {
        "rz1",
        "04_regle_zero",
        "rz1.cpp",
        "La regle de zero",
        "Cette classe ne gere aucune ressource brute : ses membres savent deja se\ncopier, se deplacer et se detruire. N'ecris donc RIEN.",
        "Supprime le destructeur vide : il empeche le compilateur de generer\nles operations de deplacement.",
        "c++20",
    },
    {
        "rz2",
        "04_regle_zero",
        "rz2.cpp",
        "La regle de cinq",
        "Des qu'on ecrit un destructeur, le compilateur cesse de generer les\noperations de DEPLACEMENT : tout retombe sur la copie.\nRedeclare-les en '= default'.",
        "Ajoute :\n  Tampon(Tampon &&) noexcept = default;\n  Tampon &operator=(Tampon &&) noexcept = default;",
        "c++20",
    },
    {
        "rz3",
        "04_regle_zero",
        "rz3.cpp",
        "Ecrire le deplacement a la main",
        "Quand on possede une ressource brute, il faut ecrire soi-meme le\ndeplacement : voler le pointeur, et laisser la source dans un etat\nvalide et destructible.",
        "Copie le pointeur et la taille, puis mets ceux de la source a nullptr\net 0. Sinon les deux objets libereront le meme bloc.",
        "c++20",
    },
    {
        "rz4",
        "04_regle_zero",
        "rz4.cpp",
        "Interdire la copie",
        "Certaines classes n'ont aucun sens copiees : un verrou, un fichier,\nune connexion. '= delete' l'interdit a la COMPILATION.",
        "Ajoute : Ressource(const Ressource &) = delete;\net l'operateur d'affectation correspondant.",
        "c++20",
    },
    {
        "rz5",
        "04_regle_zero",
        "rz5.cpp",
        "La copie superficielle",
        "Cette classe possede un bloc brut et laisse le compilateur generer la\ncopie : les deux objets pointent sur le MEME bloc, et le liberent tous\nles deux. ASan appelle ca un double-free. Ecris une copie profonde.",
        "Le constructeur de copie doit allouer son propre bloc et recopier le\ncontenu, pas recopier le pointeur.",
        "c++20",
    },
    {
        "cont1",
        "05_conteneurs",
        "cont1.cpp",
        "Taille et capacite",
        "size() est le nombre d'elements, capacity() la place reservee. Chaque\ndepassement de capacite realloue et deplace tout. reserve() evite ca\nquand on connait le nombre final.",
        "Appelle sondes.reserve(100) avant la boucle.",
        "c++20",
    },
    {
        "cont2",
        "05_conteneurs",
        "cont2.cpp",
        "L'invalidation",
        "push_back peut reallouer : toute reference, tout pointeur et tout\niterateur vers l'interieur devient invalide. ASan appelle ca un\nheap-use-after-free. Relis la valeur APRES l'ajout.",
        "Ne garde pas de pointeur a travers un push_back : indexe le vecteur\napres coup, avec nombres[0].",
        "c++20",
    },
    {
        "cont3",
        "05_conteneurs",
        "cont3.cpp",
        "emplace_back construit sur place",
        "push_back prend un objet deja fait et le copie ou le deplace.\nemplace_back recoit les arguments et construit directement dans le\nconteneur : zero copie, zero deplacement.",
        "sondes.emplace_back(i) construit la Sonde dans le vecteur.",
        "c++20",
    },
    {
        "cont4",
        "05_conteneurs",
        "cont4.cpp",
        "std::string et la petite chaine",
        "Une std::string courte ne fait aucune allocation : elle range ses octets\ndans l'objet lui-meme. C'est l'optimisation des petites chaines.\nAu-dela d'une quinzaine de caracteres, elle passe sur le tas.",
        "Une chaine de 3 caracteres tient dans l'objet ; une de 200, non.\nCompare data() a l'adresse de l'objet.",
        "c++20",
    },
    {
        "cont5",
        "05_conteneurs",
        "cont5.cpp",
        "map ou unordered_map",
        "std::map est un arbre trie : parcours ordonne, recherche en log(n).\nstd::unordered_map est une table de hachage : parcours en desordre,\nrecherche en temps constant moyen. Choisis selon ce dont tu as besoin.",
        "Ici on veut un parcours dans l'ordre des cles : c'est std::map.",
        "c++20",
    },
    {
        "cont6",
        "05_conteneurs",
        "cont6.cpp",
        "Supprimer pendant un parcours",
        "Effacer dans une boucle indexee saute des elements et invalide les\niterateurs. std::erase fait le travail en une passe, correctement.",
        "std::erase_if(nombres, [](int n) { return n % 2 == 0; });",
        "c++20",
    },
    {
        "algo1",
        "06_algos",
        "algo1.cpp",
        "Trier avec un comparateur",
        "std::sort prend un predicat 'a passe avant b'. Il doit etre un ordre\nSTRICT : comparer avec <= au lieu de < casse l'algorithme.",
        "Le comparateur renvoie true si a doit passer avant b. Pour un tri\ndecroissant : a > b.",
        "c++20",
    },
    {
        "algo2",
        "06_algos",
        "algo2.cpp",
        "Une capture qui survit a sa cible",
        "Cette lambda capture une variable locale PAR REFERENCE et sort de la\nfonction : la reference ne designe plus rien. ASan le detecte.\nCapture par valeur.",
        "Remplace [&valeur] par [valeur] : la lambda garde alors sa propre copie.",
        "c++20",
    },
    {
        "algo3",
        "06_algos",
        "algo3.cpp",
        "Chercher et accumuler",
        "find_if renvoie un iterateur sur le premier element qui satisfait le\npredicat, ou end() s'il n'y en a pas. Comparer a end() est obligatoire\navant de dereferencer.",
        "auto trouve = std::find_if(...); if (trouve != v.end()) { ... }",
        "c++20",
    },
    {
        "algo4",
        "06_algos",
        "algo4.cpp",
        "Les vues sont paresseuses",
        "Une vue de ranges ne calcule rien tant qu'on ne la parcourt pas, et ne\ncopie jamais le conteneur. Chaine un filtre et une transformation.",
        "nombres | std::views::filter(...) | std::views::transform(...)",
        "c++20",
    },
    {
        "algo5",
        "06_algos",
        "algo5.cpp",
        "std::span, une vue sur des elements",
        "std::span est un pointeur PLUS une taille : il ne possede rien, ne copie\nrien, et remplace le couple (pointeur, taille) du C.",
        "Change le parametre en std::span<const int>. Un vector et un tableau\nbrut s'y convertissent tous les deux.",
        "c++20",
    },
};

const std::vector<Question> BANQUE = {
    {
        "00_intro",
        "Devant un mur d'erreurs de template, par ou commencer ?",
        {
            "Par la derniere ligne",
            "Par la premiere ligne contenant 'error:'",
            "Par la ligne la plus longue",
            "En recompilant avec -w",
        },
        1,
        "La premiere 'error:' est la cause ; tout ce qui suit en decoule.\nCherche ensuite 'required from here' ou 'in instantiation of' : c'est la\nligne de TON code qui a declenche l'instanciation.",
    },
    {
        "01_bases",
        "Que fait 'for (auto x : conteneur)' ?",
        {
            "Une reference sur chaque element",
            "Une copie de chaque element",
            "Un pointeur sur chaque element",
            "Cela depend du conteneur",
        },
        1,
        "'auto' deduit le type sans reference ni const : chaque tour COPIE.\nSur un vector<string> de mille elements, c'est mille allocations.\nEcris 'const auto &' par defaut.",
    },
    {
        "01_bases",
        "Que contient 'std::vector<int> v{3, 5}' ?",
        {
            "Trois cases valant 5",
            "Deux cases valant 3 et 5",
            "Cinq cases valant 3",
            "Une case valant 35",
        },
        1,
        "Les accolades preferent TOUJOURS le constructeur a liste d'initialisation\nquand il existe. Pour trois cases valant 5, il faut des parentheses :\nstd::vector<int> v(3, 5).",
    },
    {
        "02_valeurs",
        "Que fait std::move au moment de l'execution ?",
        {
            "Il copie l'objet",
            "Il deplace l'objet",
            "Rien du tout",
            "Il libere l'objet source",
        },
        2,
        "std::move est un simple cast vers une reference rvalue. Il ne bouge pas\nun octet : il change la SURCHARGE choisie, et c'est le constructeur de\ndeplacement qui fait le travail — s'il existe.",
    },
    {
        "02_valeurs",
        "Pourquoi 'return std::move(local);' est-il une erreur ?",
        {
            "C'est plus lent a compiler",
            "Cela empeche l'elision de copie",
            "Cela provoque une fuite",
            "Ce n'est pas une erreur",
        },
        1,
        "Depuis C++17, un objet local renvoye est construit DIRECTEMENT chez\nl'appelant : zero copie, zero deplacement. Ajouter std::move transforme\nl'expression en rvalue et force un deplacement inutile.",
    },
    {
        "03_raii",
        "Quand le destructeur d'un objet local est-il appele ?",
        {
            "A la fin du programme",
            "Quand on appelle delete",
            "A la fermeture de l'accolade, quoi qu'il arrive",
            "Jamais si on sort par un return",
        },
        2,
        "C'est toute la garantie de RAII : return anticipe, exception, break —\nle destructeur passe. C'est pour cela qu'un unique_ptr ne fuit jamais\nla ou un delete manuel fuit.",
    },
    {
        "03_raii",
        "Que coute une copie de shared_ptr par rapport a unique_ptr ?",
        {
            "Rien",
            "Une incrementation atomique du compteur",
            "Une allocation",
            "Une copie de l'objet pointe",
        },
        1,
        "Le compteur de shared_ptr est atomique, pour rester correct entre threads.\nUne incrementation atomique coute bien plus qu'une incrementation normale.\nPasse un shared_ptr par reference constante quand tu ne stockes pas.",
    },
    {
        "04_regle_zero",
        "Que se passe-t-il quand on declare un destructeur ?",
        {
            "Rien de particulier",
            "Le compilateur cesse de generer les operations de deplacement",
            "La copie devient interdite",
            "La classe devient abstraite",
        },
        1,
        "Declarer un destructeur (meme vide, meme '= default') supprime la\ngeneration implicite du constructeur et de l'affectation de deplacement.\nTout retombe silencieusement sur la copie, et les performances avec.",
    },
    {
        "04_regle_zero",
        "La regle de zero, c'est :",
        {
            "Ne jamais ecrire de constructeur",
            "Laisser les membres gerer leurs ressources",
            "Tout mettre en private",
            "Utiliser zero allocation",
        },
        1,
        "Si chaque membre sait deja se copier, se deplacer et se detruire —\nstring, vector, unique_ptr — la classe n'a besoin d'AUCUNE des cinq\noperations. C'est la meilleure classe : celle qu'on n'ecrit pas.",
    },
    {
        "05_conteneurs",
        "Que devient un pointeur vers un element apres push_back ?",
        {
            "Il reste valide",
            "Il peut etre invalide si le vecteur a realloue",
            "Il pointe sur le nouvel element",
            "Il devient nullptr",
        },
        1,
        "Un vector garde ses elements dans un bloc continu. S'il n'y a plus de\ncapacite, il en alloue un nouveau, deplace tout, et libere l'ancien.\nTout pointeur, reference ou iterateur vers l'ancien bloc devient pendant.",
    },
    {
        "05_conteneurs",
        "Quelle est la difference entre push_back et emplace_back ?",
        {
            "Aucune",
            "emplace_back construit l'objet directement dans le conteneur",
            "push_back est plus rapide",
            "emplace_back ne fonctionne que sur les types simples",
        },
        1,
        "push_back recoit un objet deja construit et le copie ou le deplace.\nemplace_back recoit les ARGUMENTS du constructeur et construit sur place :\nune construction, zero copie, zero deplacement.",
    },
    {
        "05_conteneurs",
        "Quand preferer std::map a std::unordered_map ?",
        {
            "Quand on veut la recherche la plus rapide",
            "Quand on veut parcourir dans l'ordre des cles",
            "Quand les cles sont des chaines",
            "map est toujours preferable",
        },
        1,
        "unordered_map cherche en temps constant moyen, map en log(n). Mais map\nest un arbre trie : elle garantit un parcours ordonne, des bornes\n(lower_bound), et la stabilite des iterateurs a l'insertion.",
    },
    {
        "06_algos",
        "Que renvoie std::find_if quand rien ne correspond ?",
        {
            "nullptr",
            "L'iterateur end()",
            "Le premier element",
            "Il leve une exception",
        },
        1,
        "Toujours comparer a end() AVANT de dereferencer. Comparer a nullptr ne\ncompile meme pas sur la plupart des conteneurs : un iterateur n'est pas\nun pointeur.",
    },
    {
        "06_algos",
        "Une vue de std::ranges, ca coute :",
        {
            "Une copie du conteneur",
            "Une allocation",
            "Rien : elle est paresseuse et ne possede rien",
            "Un parcours complet a la creation",
        },
        2,
        "Une vue est un objet minuscule qui garde des iterateurs et un predicat.\nRien n'est calcule tant qu'on ne la parcourt pas, et le conteneur d'origine\nn'est ni copie ni modifie. Attention en revanche a ce qu'il lui survive.",
    },
};

}

const std::vector<Exercice> &catalogue() { return EXERCICES; }

const std::vector<Question> &questions() { return BANQUE; }
